import { StudyChapter } from '../types';

export const ENGLISH_CHAPTERS: StudyChapter[] = [
  {
    slug: 'subject-verb-agreement',
    title: 'Subject–Verb Agreement (Concord)',
    subject: 'English',
    unit: 'Unit 1: Grammar Foundation',
    category: 'Grammar Foundation',
    subcategory: 'Core Syntax',
    priority: 'High Priority',
    tier: 'Tier-I & II',
    estimatedMinutes: 45,
    rulesCount: 14,
    mcqsCount: 30,
    wordCount: 1750,
    summary: 'Mastering head noun isolation, compound conjunctions, collective nouns, proximity concord, and inverted syntax.',
    order: 1,
    nextSlug: 'noun-pronoun',
    favouriteTrap: 'Placing long plural prepositional phrases ("of the newly appointed delegates") immediately before a singular verb.',
    memoryTrick: 'Bracket the prepositional phrase [of...] to locate the real head subject standing naked at the front.',
    sections: [
      {
        title: '1. Core Concept & The Golden Rule',
        type: 'concept',
        content: 'Subject–Verb Agreement mandates that a singular subject takes a singular verb, while a plural subject takes a plural verb. In SSC CGL, errors rarely occur in simple sentences; instead, examiners embed modifiers, relative clauses, and compound prepositional phrases to deceive the candidate’s visual proximity.',
      },
      {
        title: '2. Master Rules of Subject–Verb Concord',
        type: 'rules',
        content: 'Systematic concord rules tested repeatedly in SSC error spotting:',
        rulesList: [
          {
            ruleNo: 1,
            title: 'Prepositional Phrase Interposition',
            statement: 'When words like "of", "in", "with", "for", "by" intervene between subject and verb, eliminate the phrase during analysis. The verb agrees strictly with the head noun.',
            incorrect: 'The quality of these freshly harvested apples were substandard.',
            correct: 'The quality of these freshly harvested apples was substandard.',
            trapNote: '"apples" is plural, but the head noun is "quality" (uncountable singular).',
          },
          {
            ruleNo: 2,
            title: 'Additive Connectors ("Along with", "As well as")',
            statement: 'When two subjects are joined by "as well as", "along with", "together with", "in addition to", "accompanied by", "like", "unlike", or "besides", the verb strictly agrees with the FIRST subject.',
            incorrect: 'The Prime Minister along with his cabinet colleagues are visiting the disaster site.',
            correct: 'The Prime Minister along with his cabinet colleagues is visiting the disaster site.',
            trapNote: 'Do not confuse "along with" with "and". It is an adjunct prepositional phrase.',
          },
          {
            ruleNo: 3,
            title: 'Correlative Conjunctions & Proximity Rule',
            statement: 'When two nouns/pronouns are joined by "Either...or", "Neither...nor", or "Not only...but also", the verb agrees with the subject NEAREST to it.',
            incorrect: 'Neither the principal nor the teachers was present in the auditorium.',
            correct: 'Neither the principal nor the teachers were present in the auditorium.',
            trapNote: 'In questions: "Were neither the principal nor the teachers present?"',
          },
          {
            ruleNo: 4,
            title: 'Each, Every, One of + Plural Noun + Singular Verb',
            statement: 'Expressions like "Each of", "Either of", "Neither of", "One of" are followed by a PLURAL noun/pronoun, but strictly take a SINGULAR verb.',
            incorrect: 'One of the students have submitted their thesis early.',
            correct: 'One of the students has submitted his thesis early.',
            trapNote: 'Exception: "He is one of those players who HAVE played well" (Relative pronoun "who" refers to plural antecedent "players").',
          },
        ],
      },
      {
        title: '3. Solved Examples (Step-by-Step)',
        type: 'examples',
        content: 'TCS-pattern worked questions.',
        solvedExamples: [
          {
            level: 'Moderate',
            question: 'Identify the error segment: "The introduction of tea, coffee and such other beverages (A) / have not been without some effect (B) / on the health of consumers. (C) / No error (D)"',
            solution: 'Step 1: Identify the main verb: "have not been".\nStep 2: Identify the grammatical subject: The head noun is "introduction" (singular uncountable). The words "of tea, coffee and such other beverages" are merely descriptive prepositional modifiers.\nStep 3: A singular subject ("introduction") demands a singular verb ("has not been").\nCorrect Sentence: "...has not been without some effect..."\nError is in segment (B).',
            fastTrick: 'Eliminate [of tea, coffee and beverages] ⟹ "The introduction has..."',
          },
        ],
      },
      {
        title: '4. Practice Questions',
        type: 'practice',
        content: 'Test your understanding.',
        practiceQuestions: [
          {
            id: 'sva-p-1',
            question: 'Neither the manager nor his assistants _______ present at the meeting yesterday.',
            options: ['was', 'were', 'is', 'are'],
            correctIndex: 1,
            explanation: 'With "Neither...nor", the verb agrees with the nearest subject: "his assistants" (plural) + past tense ⟹ "were".',
            sourceType: 'PYQ-style',
          },
        ],
      },
      {
        title: '5. Quick Revision Summary',
        type: 'revision',
        content: '• As well as / along with / together with ⟹ Agree with 1st subject.\n• Either...or / Neither...nor / Not only...but also ⟹ Agree with NEAREST subject.\n• One of / Each of / Neither of + Plural Noun ⟹ Singular Verb.\n• One of the + Plural Noun + Who/That ⟹ Plural Verb.',
      },
    ],
  },
  {
    slug: 'noun-pronoun',
    title: 'Noun & Pronoun: Case Concord, Uncountable Traps & Relative Pronouns',
    subject: 'English',
    unit: 'Unit 1: Grammar Foundation',
    category: 'Grammar Foundation',
    subcategory: 'Parts of Speech',
    priority: 'High Priority',
    tier: 'Tier-I & II',
    estimatedMinutes: 45,
    rulesCount: 15,
    mcqsCount: 35,
    wordCount: 1800,
    summary: 'Uncountable noun lists (scenery, furniture, luggage), compound plural rules, apostrophe usage traps, personal pronoun order 231 vs 123, and Who vs Whom.',
    order: 2,
    prevSlug: 'subject-verb-agreement',
    nextSlug: 'tenses',
    favouriteTrap: 'Pluralizing uncountable nouns (e.g. sceneries, furnitures, informations) or using "Whom" as subject of a subsequent finite verb.',
    memoryTrick: 'Pronoun sequence in good deeds: 2-3-1 (You, he and I). Pronoun sequence in confession/fault: 1-2-3 (I, you and he).',
    sections: [
      {
        title: '1. Uncountable Nouns Never Taking Plural "s" or "a/an"',
        type: 'concept',
        content: 'The following nouns are strictly UNCOUNTABLE in English. They cannot take an indefinite article ("a/an") before them, nor can they take plural "s/es":\n• Scenery, Furniture, Luggage, Baggage, Information, Advice, Machinery, Poetry, Stationery, Jewellery, Hair, Bread, Crockery, Confectionery, Garbage, Wastage.\n\nTo denote quantity, use: "a piece of furniture", "two pieces of advice", "loaves of bread", "articles of luggage".',
      },
      {
        title: '2. High-Yield Noun & Pronoun Concord Rules',
        type: 'rules',
        content: 'Core grammar rules tested in SSC CGL:',
        rulesList: [
          {
            ruleNo: 1,
            title: 'Nouns Plural in Form but Singular in Meaning',
            statement: 'Nouns ending in "s" that take a singular verb:\n• Subjects: Mathematics, Physics, Economics, Civics, Statistics, Politics.\n• Diseases: Measles, Mumps, Rickets, Shingles.\n• Sports/Games: Billiards, Darts, Chess.\n• Others: News, Innings, Summons (Plural is Summonses).',
            incorrect: 'Mathematics are a difficult subject for many aspirants.',
            correct: 'Mathematics is a difficult subject for many aspirants.',
            trapNote: 'Exception: When qualified by a possessive pronoun ("His mathematics are weak"), it means mathematical calculations/ability and takes a plural verb.',
          },
          {
            ruleNo: 2,
            title: 'Personal Pronoun Sequence: 231 vs 123',
            statement: '• Normal / Pleasant contexts: Second Person (2) + Third Person (3) + First Person (1) ⟹ "You, he and I".\n• Negative contexts / Confession of fault / Plural pronouns: First Person (1) + Second Person (2) + Third Person (3) ⟹ "I, you and he" or "We, you and they".',
            incorrect: 'I, you and he will celebrate the festival together.',
            correct: 'You, he and I will celebrate the festival together.',
            trapNote: 'Always follow 2-3-1 unless confessing a crime, mistake, or guilt.',
          },
          {
            ruleNo: 3,
            title: 'Relative Pronouns: Who vs Whom vs That',
            statement: '• "Who" is a SUBJECTIVE pronoun (takes a finite verb: Who called you?).\n• "Whom" is an OBJECTIVE pronoun (receives action or follows a preposition: To whom did you speak?).\n• "That" is mandatory instead of who/which after: All, None, Only, Same, Superlative degrees (The best book that I read).',
            incorrect: 'He is the candidate whom I think will win the election.',
            correct: 'He is the candidate who I think will win the election.',
            trapNote: 'In "who I think will win", remove parenthetical "I think" to see that "who" is the subject of "will win".',
          },
        ],
      },
      {
        title: '3. Solved Examples (Step-by-Step)',
        type: 'examples',
        content: 'Exam-calibrated solved questions.',
        solvedExamples: [
          {
            level: 'Moderate',
            question: 'Find the error: "The sceneries of Kashmir (A) / are so enchanting (B) / that they mesmerize every tourist. (C) / No error (D)"',
            solution: '"Scenery" is an uncountable noun that has no plural form. It cannot be written as "sceneries". Furthermore, being an uncountable singular noun, it takes a singular verb "is", not "are".\nCorrect Sentence: "The scenery of Kashmir is so enchanting..."\nError is in segment (A) and (B).',
            fastTrick: 'Scenery is uncountable. Never write "sceneries".',
          },
        ],
      },
      {
        title: '4. Quick Revision Summary',
        type: 'revision',
        content: '• Uncountable: Scenery, Furniture, Advice, Information, Luggage, Baggage (No "s", no "a/an").\n• Pronoun order in positive: 2-3-1 (You, he and I).\n• Pronoun order in mistake/guilt: 1-2-3 (I, you and he).\n• Summons is singular; Summonses is plural.\n• After "All", "The only", "The same", use relative pronoun "THAT" (not which/who).',
      },
    ],
  },
  {
    slug: 'tenses',
    title: 'Tenses & Time-Frame Aspect Structures',
    subject: 'English',
    unit: 'Unit 1: Grammar Foundation',
    category: 'Grammar Foundation',
    subcategory: 'Temporal Mechanics',
    priority: 'High Priority',
    tier: 'Tier-I & II',
    estimatedMinutes: 50,
    rulesCount: 16,
    mcqsCount: 35,
    wordCount: 1850,
    summary: 'Mastering the 12 tense matrix, stative verbs not taking continuous form, past perfect precedence, and since vs for duration markers.',
    order: 3,
    prevSlug: 'noun-pronoun',
    nextSlug: 'conditionals',
    favouriteTrap: 'Using present perfect ("has died") with specific past time adverbs ("yesterday", "in 1947", "two days ago").',
    memoryTrick: 'Specific past time marker (yesterday, ago, last week, in 2010) = ALWAYS Simple Past (V2), NEVER Present Perfect.',
    sections: [
      {
        title: '1. Master Tense Matrix Table',
        type: 'concept',
        content: 'Complete overview of English tense aspects:',
        table: {
          title: 'The 12 English Tenses: Structure & Time Keywords',
          headers: ['Tense Aspect', 'Active Structure', 'Exam Time Markers', 'Key Usage Context'],
          rows: [
            ['Simple Present', 'Subject + V1/V1(s/es)', 'Always, usually, generally, daily, seldom, never', 'Universal truths, scientific laws, habitual daily routines'],
            ['Present Continuous', 'Subject + is/am/are + V-ing', 'Now, right now, at present, currently, nowadays', 'Action occurring at the moment of speaking (not for stative verbs)'],
            ['Present Perfect', 'Subject + has/have + V3', 'Already, just now, recently, yet, so far, up to now', 'Action completed in past with connection to present (NO past time adverbs)'],
            ['Present Perfect Cont.', 'Subject + has/have been + V-ing', 'Since (point of time), For (period of duration)', 'Action began in past and continues into present'],
            ['Simple Past', 'Subject + V2', 'Yesterday, ago, last night, in 1947, previous day', 'Completed past action with explicit or implied past time point'],
            ['Past Continuous', 'Subject + was/were + V-ing', 'While, when, at that time', 'Ongoing action in the past interrupted by another action'],
            ['Past Perfect', 'Subject + had + V3', 'Before, after, by the time', 'Earlier of two past actions (Preceding Past)'],
            ['Past Perfect Cont.', 'Subject + had been + V-ing', 'Since, for (with past context)', 'Ongoing action in past up to a specific past moment'],
            ['Simple Future', 'Subject + will/shall + V1', 'Tomorrow, next week, soon, shortly', 'Pure future intent or prediction'],
            ['Future Perfect', 'Subject + will/shall have + V3', 'By + future time (e.g. "by 2026", "by tomorrow")', 'Action that will be completed prior to a designated future time'],
          ],
        },
      },
      {
        title: '2. Stative Verbs Not Used in Continuous Tense',
        type: 'rules',
        content: 'Verbs expressing state, perception, or emotion do not take continuous (-ing) forms in standard English:',
        rulesList: [
          {
            ruleNo: 1,
            title: 'Verbs of Perception & Cognition',
            statement: 'See, hear, smell, notice, recognize, know, understand, believe, remember, doubt, forget, prefer take simple tenses.',
            incorrect: 'I am knowing the answer to this question.',
            correct: 'I know the answer to this question.',
            trapNote: 'Exception: "The judge is hearing the case tomorrow" (formal trial), "I am seeing the doctor" (visiting appointment).',
          },
          {
            ruleNo: 2,
            title: 'Past Perfect Precedence with "Before" & "After"',
            statement: 'When two actions occurred in the past:\n• 1st Action (Earlier Past) = Past Perfect (Had + V3)\n• 2nd Action (Subsequent Past) = Simple Past (V2).',
            incorrect: 'The train departed before I reached the platform.',
            correct: 'The train had departed before I reached the platform.',
            trapNote: 'Formula: [1st Action: Had + V3] BEFORE [2nd Action: V2].',
          },
        ],
      },
      {
        title: '3. Solved Examples (Step-by-Step)',
        type: 'examples',
        content: 'Worked questions from recent SSC exams.',
        solvedExamples: [
          {
            level: 'Moderate',
            question: 'Identify the error: "He has left (A) / for Mumbai (B) / yesterday evening. (C) / No error (D)"',
            solution: 'The sentence contains the specific past time adverb "yesterday evening". Specific past time markers are incompatible with Present Perfect tense ("has left"). They require Simple Past tense (V2: "left").\nCorrect Sentence: "He left for Mumbai yesterday evening."\nError is in segment (A).',
            fastTrick: '"Yesterday" = Simple Past (V2), never Present Perfect.',
          },
        ],
      },
      {
        title: '4. Quick Revision Summary',
        type: 'revision',
        content: '• Specific past time marker (yesterday, ago, in 1990) ⟹ Simple Past (V2).\n• "Since" denotes starting point of time; "For" denotes duration of time.\n• Stative verbs (know, love, understand, own) do not take continuous -ing.\n• Earlier past = Had + V3; Later past = V2.',
      },
    ],
  },
  {
    slug: 'conditionals',
    title: 'Conditionals & Hypothetical Subjunctive Mood',
    subject: 'English',
    unit: 'Unit 1: Grammar Foundation',
    category: 'Grammar Foundation',
    subcategory: 'Hypothetical Mood',
    priority: 'High Priority',
    tier: 'Tier-I & II',
    estimatedMinutes: 40,
    rulesCount: 10,
    mcqsCount: 30,
    wordCount: 1550,
    summary: 'Zero, First, Second, Third, and Mixed Conditionals, subjunctive "were" for all persons, and inverted conditional clauses.',
    order: 4,
    prevSlug: 'tenses',
    nextSlug: 'prepositions',
    favouriteTrap: 'Using "would have" inside the If-clause ("If he would have arrived on time").',
    memoryTrick: 'NEVER put "would" inside the conditional If-clause! "If + Had + V3 ... would have + V3".',
    sections: [
      {
        title: '1. Master Conditionals Formula Table',
        type: 'concept',
        content: 'The 4 standard conditional architectures:',
        table: {
          title: 'Classification of Conditional Sentences in English',
          headers: ['Type', 'If-Clause (Condition)', 'Main Clause (Result)', 'Meaning / Realism'],
          rows: [
            ['Zero Conditional', 'If + Simple Present (V1)', 'Simple Present (V1)', 'Universal scientific truth / Automatic cause and effect'],
            ['First Conditional', 'If + Simple Present (V1)', 'Will / Shall / Can + V1', 'Real and probable future possibility'],
            ['Second Conditional', 'If + Simple Past (V2 / Were)', 'Would / Could + V1', 'Hypothetical / Unreal present or future condition'],
            ['Third Conditional', 'If + Past Perfect (Had + V3)', 'Would have / Could have + V3', 'Unreal, impossible past condition with past consequence'],
            ['Inversion (Third)', 'Had + Subject + V3', 'Subject + would have + V3', 'Formal conditional without "If"'],
          ],
        },
      },
      {
        title: '2. SSC Golden Rules for Conditionals',
        type: 'rules',
        content: 'Rules for spotting errors in conditionals:',
        rulesList: [
          {
            ruleNo: 1,
            title: 'No "Would" in the If-Clause',
            statement: 'The If-clause can NEVER contain modal auxiliaries like "would", "would have", or "will".',
            incorrect: 'If he would have worked hard, he would have passed the exam.',
            correct: 'If he had worked hard, he would have passed the exam.',
            trapNote: 'This is the #1 most repeated error in SSC CGL exams.',
          },
          {
            ruleNo: 2,
            title: 'Subjunctive "Were" for All Subjects',
            statement: 'In hypothetical / imaginary conditions, use "were" for all singular and plural subjects (including I, he, she, it).',
            incorrect: 'If I was the Prime Minister, I would eliminate corruption.',
            correct: 'If I were the Prime Minister, I would eliminate corruption.',
            trapNote: 'Even with singular pronouns, unreal subjunctive requires "were".',
          },
        ],
      },
      {
        title: '3. Solved Examples',
        type: 'examples',
        content: 'TCS solved problems.',
        solvedExamples: [
          {
            level: 'Moderate',
            question: 'Identify the error: "Had the police arrived in time (A) / they would save (B) / the victim from the mob. (C) / No error (D)"',
            solution: 'The sentence employs inverted Third Conditional: "Had the police arrived..." (Had + Subject + V3). The corresponding main clause MUST contain "would have + V3", not "would save".\nCorrect Sentence: "...they would have saved the victim..."\nError is in segment (B).',
            fastTrick: 'Had + V3 requires "would have + V3".',
          },
        ],
      },
      {
        title: '4. Quick Revision Summary',
        type: 'revision',
        content: '• If + V1 ⟹ will + V1.\n• If + V2 / were ⟹ would + V1.\n• If + had + V3 ⟹ would have + V3.\n• Had + S + V3 ⟹ S + would have + V3 (Inversion).\n• Never put "would" or "will" inside the If-clause.',
      },
    ],
  },
  {
    slug: 'prepositions',
    title: 'Prepositions: Core Usages & Master Fixed List',
    subject: 'English',
    unit: 'Unit 1: Grammar Foundation',
    category: 'Grammar Foundation',
    subcategory: 'Collocations & Phrasal Usage',
    priority: 'High Priority',
    tier: 'Tier-I & II',
    estimatedMinutes: 50,
    rulesCount: 22,
    mcqsCount: 40,
    wordCount: 1950,
    summary: 'Fixed prepositions catalog (accustomed to, abstain from, adhere to), verbs taking no prepositions, and subtle distinction traps.',
    order: 5,
    prevSlug: 'conditionals',
    nextSlug: 'active-passive-voice',
    favouriteTrap: 'Adding superfluous prepositions after transitive verbs: "comprises of", "ordered for", "entered into the room".',
    memoryTrick: 'Verbs that absorb their preposition in active voice: Comprise (no of), Order (no for), Discuss (no about), Enter (no into for physical room).',
    sections: [
      {
        title: '1. Transitive Verbs That Take NO Preposition in Active Voice',
        type: 'concept',
        content: 'Certain transitive verbs act directly on their objects. Inserting a preposition after them is a grave grammatical error:\n• Comprise (NOT comprise of)\n• Order (NOT order for a coffee)\n• Discuss (NOT discuss about the matter)\n• Describe (NOT describe about the incident)\n• Enter (NOT enter into the room — Note: enter into an agreement/discussion is an idiomatic exception)\n• Resemble (NOT resemble with/to)\n• Attack (NOT attack on the enemy)\n• Marry (NOT marry with her — In passive: "He was married to her" is correct).',
      },
      {
        title: '2. High-Frequency Fixed Prepositions Table',
        type: 'concept',
        content: 'Memorize these 25 essential fixed prepositions frequently tested in SSC CGL:',
        table: {
          title: 'Master Fixed Prepositions for SSC CGL',
          headers: ['Expression / Verb', 'Governing Preposition', 'Exam Context Example'],
          rows: [
            ['Abstain / Refrain', 'FROM + Gerund', 'He abstained from smoking.'],
            ['Accustomed / Addicted', 'TO + Gerund', 'She is accustomed to working late.'],
            ['Adhere / Comply', 'TO / WITH', 'Adhere to rules; Comply with regulations.'],
            ['Congratulate', 'ON', 'Congratulate you on your spectacular success.'],
            ['Cope', 'WITH (NOT "cope up with")', 'He found it difficult to cope with the stress.'],
            ['Deprive', 'OF', 'Deprived of basic human rights.'],
            ['Different', 'FROM (NOT "different than")', 'This method is different from that one.'],
            ['Look forward to', 'TO + Gerund', 'Looking forward to meeting you.'],
            ['Object', 'TO + Gerund', 'Object to paying extra fees.'],
            ['Prevent / Prohibit', 'FROM + Gerund', 'Prevented him from entering the premises.'],
            ['Rely / Depend', 'ON / UPON', 'Rely upon your own efforts.'],
            ['Senior / Junior / Superior', 'TO (NOT "than")', 'He is senior to me by three years.'],
            ['Subordinate', 'TO', 'Subordinate to the director.'],
            ['Yield / Surrender', 'TO', 'The rebel refused to yield to pressure.'],
          ],
        },
      },
      {
        title: '3. Solved Examples (Step-by-Step)',
        type: 'examples',
        content: 'Standard SSC error spotting examples.',
        solvedExamples: [
          {
            level: 'Moderate',
            question: 'Identify the error: "Our new committee (A) / comprises of seven (B) / distinguished senior academicians. (C) / No error (D)"',
            solution: 'The transitive verb "comprise" means "consist of". In the active voice, it takes a direct object without the preposition "of".\nCorrect Sentence: "...comprises seven distinguished senior academicians."\nError is in segment (B).',
            fastTrick: 'Comprise = Consist of. Never write "comprise of".',
          },
        ],
      },
      {
        title: '4. Quick Revision Summary',
        type: 'revision',
        content: '• Comprise, order, discuss, describe take NO preposition in active voice.\n• Abstain from, refrain from, prevent from + Gerund (V-ing).\n• Look forward to, accustomed to, with a view to + Gerund (V-ing).\n• Senior, junior, superior, inferior take TO (never than).\n• Cope with (never "cope up with").',
      },
    ],
  },
  {
    slug: 'active-passive-voice',
    title: 'Active & Passive Voice: Transformation Algorithms & Modals',
    subject: 'English',
    unit: 'Unit 2: Transformational Grammar',
    category: 'Grammar Transformation',
    subcategory: 'Voice & Syntax',
    priority: 'High Priority',
    tier: 'Tier-I & II',
    estimatedMinutes: 45,
    rulesCount: 12,
    mcqsCount: 35,
    wordCount: 1800,
    summary: 'Universal active to passive formula, 8 transformable tenses, modals in passive, imperative conversions (Let + be + V3), and quasi-passive verbs.',
    order: 6,
    prevSlug: 'prepositions',
    nextSlug: 'direct-indirect-speech',
    favouriteTrap: 'Changing the tense during voice transformation (Tense NEVER changes in Active-Passive; tense changes only in Direct-Indirect Narration).',
    memoryTrick: 'Golden Voice Rule: The passive ALWAYS contains a form of "Be" + Past Participle (V3). Tense stays identically anchored!',
    sections: [
      {
        title: '1. The Universal Passive Transformation Formula',
        type: 'concept',
        content: 'To convert Active into Passive:\n1. Object of active becomes the Subject of passive.\n2. Add appropriate form of auxiliary "BE" matching the tense and new subject.\n3. Convert main verb into its Past Participle form (V3).\n4. Add preposition "by" (or other fixed preposition) before the original active subject.\n\nCrucial Fact: 4 tenses CANNOT be converted into passive in standard English: Present Perfect Continuous, Past Perfect Continuous, Future Continuous, and Future Perfect Continuous.',
      },
      {
        title: '2. Tense-by-Tense Voice Transformation Matrix',
        type: 'concept',
        content: 'The 8 transformable tenses in English:',
        table: {
          title: 'Active to Passive Conversion Matrix across Tenses',
          headers: ['Tense', 'Active Voice Pattern', 'Passive Voice Pattern', 'Example Transformation'],
          rows: [
            ['Simple Present', 'Subject + V1/V1(s/es) + Object', 'Object + is/am/are + V3 + by + Subject', 'He writes a letter ⟹ A letter is written by him.'],
            ['Present Continuous', 'Subject + is/am/are + V-ing + Object', 'Object + is/am/are + BEING + V3 + by + Subject', 'He is writing a letter ⟹ A letter is being written by him.'],
            ['Present Perfect', 'Subject + has/have + V3 + Object', 'Object + has/have + BEEN + V3 + by + Subject', 'He has written a letter ⟹ A letter has been written by him.'],
            ['Simple Past', 'Subject + V2 + Object', 'Object + was/were + V3 + by + Subject', 'He wrote a letter ⟹ A letter was written by him.'],
            ['Past Continuous', 'Subject + was/were + V-ing + Object', 'Object + was/were + BEING + V3 + by + Subject', 'He was writing a letter ⟹ A letter was being written by him.'],
            ['Past Perfect', 'Subject + had + V3 + Object', 'Object + had + BEEN + V3 + by + Subject', 'He had written a letter ⟹ A letter had been written by him.'],
            ['Simple Future', 'Subject + will/shall + V1 + Object', 'Object + will/shall + BE + V3 + by + Subject', 'He will write a letter ⟹ A letter will be written by him.'],
            ['Future Perfect', 'Subject + will have + V3 + Object', 'Object + will have + BEEN + V3 + by + Subject', 'He will have written a letter ⟹ A letter will have been written by him.'],
            ['Modals', 'Subject + Modal + V1 + Object', 'Object + Modal + BE + V3 + by + Subject', 'You must finish this ⟹ This must be finished by you.'],
          ],
        },
      },
      {
        title: '3. Imperatives & Quasi-Passive Verbs',
        type: 'rules',
        content: 'Special sentence forms in voice transformation:',
        rulesList: [
          {
            ruleNo: 1,
            title: 'Imperative Orders & Commands: Let + Object + Be + V3',
            statement: 'For orders/commands with an object: "Close the door" ⟹ "Let the door be closed". For advice/moral duty: "Help the poor" ⟹ "The poor should be helped".',
            incorrect: 'Closing the door is required by you.',
            correct: 'Let the door be closed.',
            trapNote: 'If no object exists (e.g. "Go away"), use: "You are ordered to go away".',
          },
          {
            ruleNo: 2,
            title: 'Quasi-Passive Verbs (Taste, Smell, Feel)',
            statement: 'Verbs of sensation: "Quinine tastes bitter" ⟹ "Quinine is bitter when it is tasted". "Rose smells sweet" ⟹ "Rose is sweet when it is smelt".',
            incorrect: 'Bitter is tasted by Quinine.',
            correct: 'Quinine is bitter when it is tasted.',
            trapNote: 'Retain the descriptive adjective before adding "when it is V3".',
          },
        ],
      },
      {
        title: '4. Solved Examples (Step-by-Step)',
        type: 'examples',
        content: 'TCS exam-level voice questions.',
        solvedExamples: [
          {
            level: 'Moderate',
            question: 'Convert to Passive: "Who taught you English?"\n(A) By whom were you taught English?\n(B) By whom was English taught you?\n(C) By who you were taught English?\n(D) English was taught to you by whom?',
            solution: '"Who" transforms into "By whom". The sentence is in Simple Past (V2: "taught"). In interrogative passive, auxiliary verb precedes the subject: "By whom were you taught English?"\nCorrect Answer: (A)',
            fastTrick: 'Who ⟹ By whom + auxiliary + subject + V3.',
          },
        ],
      },
      {
        title: '5. Quick Revision Summary',
        type: 'revision',
        content: '• TENSE NEVER CHANGES in Active-Passive voice transformations.\n• Continuous tenses always add BEING in passive.\n• Perfect tenses always add BEEN in passive.\n• Modals take modal + BE + V3.\n• Imperatives with object take: Let + Object + be + V3.',
      },
    ],
  },
  {
    slug: 'direct-indirect-speech',
    title: 'Direct & Indirect Speech (Narration & Tense Shifts)',
    subject: 'English',
    unit: 'Unit 2: Transformational Grammar',
    category: 'Grammar Transformation',
    subcategory: 'Narration & Discourse',
    priority: 'High Priority',
    tier: 'Tier-I & II',
    estimatedMinutes: 45,
    rulesCount: 14,
    mcqsCount: 35,
    wordCount: 1850,
    summary: 'Reporting verb conditions, tense backshifting rules, universal truth exceptions, pronoun conversions (SON formula), and interrogative reporting.',
    order: 7,
    prevSlug: 'active-passive-voice',
    favouriteTrap: 'Backshifting tense when reporting universal scientific facts (e.g. converting "Earth revolves around the Sun" into "revolved").',
    memoryTrick: 'SON Formula for Pronoun Shifts: 1st Person changes according to Subject; 2nd Person changes according to Object; 3rd Person has NO change (S-O-N = 1-2-3).',
    sections: [
      {
        title: '1. Reporting Verb Conditions & Tense Shifts',
        type: 'concept',
        content: 'The Golden Rule of Narration:\n• If the Reporting Verb is in Present or Future tense (e.g. says, will say), the tense of the Reported Speech NEVER changes!\n• If the Reporting Verb is in Past tense (e.g. said, told), the tense of the Reported Speech backshifts into its corresponding past aspect:\n  - Simple Present (V1) ⟹ Simple Past (V2)\n  - Present Continuous (is/am/are) ⟹ Past Continuous (was/were)\n  - Present Perfect (has/have + V3) ⟹ Past Perfect (had + V3)\n  - Simple Past (V2) ⟹ Past Perfect (had + V3)\n  - Past Continuous (was/were + V-ing) ⟹ Past Perfect Continuous (had been + V-ing)\n  - Past Perfect (had + V3) ⟹ Remains Past Perfect (NO CHANGE)\n  - Will ⟹ Would; Can ⟹ Could; May ⟹ Might; Shall ⟹ Should.',
      },
      {
        title: '2. The Universal Truth Exception',
        type: 'rules',
        content: 'When reported speech expresses a universal truth, scientific fact, historical constant, or habitual fact, the tense remains in Simple Present EVEN IF the reporting verb is in the past:',
        rulesList: [
          {
            ruleNo: 1,
            title: 'Invariable Truths',
            statement: 'Do not alter the tense of scientific laws, universal truths, or proverbs.',
            incorrect: 'The teacher said that the Earth revolved around the Sun.',
            correct: 'The teacher said that the Earth revolves around the Sun.',
            trapNote: 'SSC examiners intentionally set options with past tense to bait candidates.',
          },
        ],
      },
      {
        title: '3. Master Time & Place Adverbial Shifts Table',
        type: 'concept',
        content: 'Words denoting proximity shift to words denoting distance in indirect speech:',
        table: {
          title: 'Adverbial Changes in Indirect Narration',
          headers: ['Direct Speech Word', 'Indirect Speech Transformation'],
          rows: [
            ['Now', 'Then'],
            ['Today', 'That day'],
            ['Yesterday', 'The previous day / The day before'],
            ['Tomorrow', 'The next day / The following day'],
            ['Tonight', 'That night'],
            ['Last night', 'The previous night'],
            ['This / These', 'That / Those'],
            ['Here', 'There'],
            ['Ago', 'Before'],
            ['Hence', 'Thence / Thus'],
          ],
        },
      },
      {
        title: '4. Solved Examples (Step-by-Step)',
        type: 'examples',
        content: 'SSC CGL narration problems.',
        solvedExamples: [
          {
            level: 'Moderate',
            question: 'Convert to Indirect Speech: He said, "I have completed my assignment today."\n(A) He said that he has completed his assignment today.\n(B) He said that he had completed his assignment that day.\n(C) He said that he completed his assignment that day.\n(D) He said that I had completed my assignment that day.',
            solution: 'Step 1: Reporting verb "said" is in Past tense ⟹ apply backshifting.\nStep 2: "have completed" (Present Perfect) becomes "had completed" (Past Perfect).\nStep 3: Pronoun "I" changes according to subject ("He"); "my" becomes "his".\nStep 4: Adverb "today" shifts to "that day".\nCombining: He said that he had completed his assignment that day.\nCorrect Answer: (B)',
            fastTrick: 'has/have ⟹ had; today ⟹ that day.',
          },
        ],
      },
      {
        title: '5. Quick Revision Summary',
        type: 'revision',
        content: '• Present/Future reporting verb = NO tense change.\n• Past reporting verb = Backshift all tenses (V1→V2; V2→had+V3; has/have→had).\n• Universal truths & scientific facts NEVER backshift.\n• SON: 1st person→Subject, 2nd person→Object, 3rd person→No change.\n• Interrogatives: "if/whether" for Yes/No questions; NO "that" before wh-words.',
      },
    ],
  },
];
