import { MathFormulaItem } from '../types';

export const MATH_FORMULAS: MathFormulaItem[] = [
  {
    id: 'f-incircle-right',
    title: 'Incircle Radius in a Right-Angled Triangle',
    category: 'Geometry',
    topic: 'Triangles',
    latex: 'r = \\frac{a + b - c}{2} = s - c',
    plainText: 'r = (a + b - c) / 2',
    variables: [
      { symbol: 'a, b', meaning: 'Lengths of the perpendicular sides (base and height)' },
      { symbol: 'c', meaning: 'Length of the hypotenuse' },
      { symbol: 's', meaning: 'Semi-perimeter = (a + b + c) / 2' },
      { symbol: 'r', meaning: 'Incircle radius (inradius)' },
    ],
    whenToUse: 'Direct questions giving side lengths of right triangle (e.g. 5-12-13 or 7-24-25) asking for the inscribed circle radius.',
    commonTrap: 'Forgetting that c is the hypotenuse. Do NOT subtract a perpendicular leg.',
  },
  {
    id: 'f-equilateral-radii',
    title: 'Equilateral Triangle Inradius and Circumradius',
    category: 'Geometry',
    topic: 'Triangles',
    latex: 'r = \\frac{a}{2\\sqrt{3}}, \\quad R = \\frac{a}{\\sqrt{3}}, \\quad \\frac{R}{r} = 2',
    plainText: 'r = a / (2√3), R = a / √3, R : r = 2 : 1',
    variables: [
      { symbol: 'a', meaning: 'Side length of the equilateral triangle' },
      { symbol: 'r', meaning: 'Inradius (inside circle radius)' },
      { symbol: 'R', meaning: 'Circumradius (outside circle radius)' },
    ],
    whenToUse: 'Ratio of areas of circumcircle to incircle in equilateral triangle is always R^2 / r^2 = 4 : 1.',
    commonTrap: 'Confusing 2√3 in denominator with √3. Inradius is smaller, so it has 2 in the denominator.',
  },
  {
    id: 'f-ptolemy',
    title: "Ptolemy's Theorem for Cyclic Quadrilateral",
    category: 'Geometry',
    topic: 'Circles & Quadrilaterals',
    latex: 'd_1 \\times d_2 = (a \\times c) + (b \\times d)',
    plainText: 'd1 × d2 = (a × c) + (b × d)',
    variables: [
      { symbol: 'd1, d2', meaning: 'Lengths of the two diagonals' },
      { symbol: 'a, b, c, d', meaning: 'Lengths of the four sides taken in consecutive order' },
    ],
    whenToUse: 'When all 4 sides of a cyclic quadrilateral (vertices on a circle) are known and product of diagonals is required.',
    commonTrap: 'Applies ONLY to cyclic quadrilaterals (quadrilaterals inscribable in a circle), not arbitrary four-sided figures.',
  },
  {
    id: 'f-brahmagupta',
    title: "Brahmagupta's Formula for Area of Cyclic Quadrilateral",
    category: 'Mensuration 2D',
    topic: 'Quadrilaterals',
    latex: '\\text{Area} = \\sqrt{(s - a)(s - b)(s - c)(s - d)}, \\quad s = \\frac{a + b + c + d}{2}',
    plainText: 'Area = √[(s - a)(s - b)(s - c)(s - d)] where s = (a + b + c + d) / 2',
    variables: [
      { symbol: 'a, b, c, d', meaning: 'Side lengths' },
      { symbol: 's', meaning: 'Semi-perimeter of quadrilateral' },
    ],
    whenToUse: 'To find area of a cyclic quadrilateral directly from the lengths of its four sides without knowing angle values.',
    commonTrap: 'Do not multiply by s at the front. Unlike Heron’s triangle formula which has s(s-a)(s-b)(s-c), Brahmagupta has no lone s.',
  },
  {
    id: 'f-delta-pct',
    title: 'Percentage Base-Shift Reciprocal Delta',
    category: 'Arithmetic',
    topic: 'Percentage',
    latex: '+\\frac{1}{x} \\;\\text{increase} \\iff -\\frac{1}{x + 1} \\;\\text{decrease}',
    plainText: '+1/x increase corresponds to -1/(x+1) decrease',
    variables: [
      { symbol: '1/x', meaning: 'Fractional increase in price or first variable' },
      { symbol: '1/(x+1)', meaning: 'Fractional reduction needed in consumption to maintain constant expenditure' },
    ],
    whenToUse: 'Questions of the form: "Price of sugar rises by 25% (+1/4). By how much must consumption decrease? -> 1/(4+1) = 1/5 = 20%".',
    commonTrap: 'Applying the same percentage decrease as the increase. 25% up requires 20% down, not 25% down.',
  },
  {
    id: 'f-successive-pct',
    title: 'Successive Percentage Net Change Formula',
    category: 'Arithmetic',
    topic: 'Percentage & Discount',
    latex: '\\text{Net \\%} = a + b + \\frac{a \\times b}{100}',
    plainText: 'Net % = a + b + (ab / 100)',
    variables: [
      { symbol: 'a', meaning: 'First percentage change (positive for increase, negative for decrease)' },
      { symbol: 'b', meaning: 'Second percentage change' },
    ],
    whenToUse: 'Successive discounts, successive taxes, population changes over 2 years.',
    commonTrap: 'For discounts, remember a and b are negative: -d1 - d2 + (d1*d2)/100 = -(d1 + d2 - d1*d2/100).',
  },
  {
    id: 'f-ci-si-diff-2yr',
    title: 'Difference Between CI and SI for 2 Years',
    category: 'Arithmetic',
    topic: 'Simple & Compound Interest',
    latex: 'D_2 = P \\left(\\frac{R}{100}\\right)^2',
    plainText: 'D2 = P * (R / 100)^2',
    variables: [
      { symbol: 'D2', meaning: 'Difference between CI and SI over exactly 2 years' },
      { symbol: 'P', meaning: 'Principal sum' },
      { symbol: 'R', meaning: 'Annual rate of interest percentage' },
    ],
    whenToUse: 'SSC favorite question giving D2 and R, asking for Principal P.',
    commonTrap: 'This applies only for 2 years. For 3 years, multiply by (3 + R/100): D3 = P(R/100)^2 * (300 + R)/100.',
  },
  {
    id: 'f-algebra-cubic',
    title: 'Cubic Symmetric Identity with Zero Sum Condition',
    category: 'Advanced Quant',
    topic: 'Algebra',
    latex: 'a^3 + b^3 + c^3 - 3abc = (a + b + c)(a^2 + b^2 + c^2 - ab - bc - ca)',
    plainText: 'a^3 + b^3 + c^3 - 3abc = (a + b + c)(a^2 + b^2 + c^2 - ab - bc - ca)',
    variables: [
      { symbol: 'a, b, c', meaning: 'Real numbers or algebraic expressions' },
      { symbol: 'Special Case', meaning: 'If a + b + c = 0, then a^3 + b^3 + c^3 = 3abc' },
    ],
    whenToUse: 'Expressions where terms add up to zero (e.g., (x-y)^3 + (y-z)^3 + (z-x)^3 = 3(x-y)(y-z)(z-x)).',
    commonTrap: 'Forgetting the factor 1/2 in the alternative form: (1/2)(a+b+c)[(a-b)^2 + (b-c)^2 + (c-a)^2].',
  },
  {
    id: 'f-trig-pythagorean',
    title: 'Fundamental Pythagorean Trigonometric Identities',
    category: 'Advanced Quant',
    topic: 'Trigonometry',
    latex: '\\sin^2\\theta + \\cos^2\\theta = 1, \\quad \\sec^2\\theta - \\tan^2\\theta = 1, \\quad \\csc^2\\theta - \\cot^2\\theta = 1',
    plainText: 'sin²θ + cos²θ = 1, sec²θ - tan²θ = 1, csc²θ - cot²θ = 1',
    variables: [
      { symbol: 'θ', meaning: 'Angle in degrees or radians' },
      { symbol: 'sec θ + tan θ', meaning: 'Reciprocal of (sec θ - tan θ): (sec θ + tan θ) = 1 / (sec θ - tan θ)' },
    ],
    whenToUse: 'When sec θ + tan θ = p is given; sec θ - tan θ = 1/p, then adding gives 2 sec θ = p + 1/p.',
    commonTrap: 'Writing sec²θ + tan²θ = 1. It is a SUBTRACTION: sec²θ - tan²θ = 1.',
  },
  {
    id: 'f-speed-relative',
    title: 'Relative Speed of Trains and Moving Objects',
    category: 'Arithmetic',
    topic: 'Time Speed Distance',
    latex: 'S_{\\text{rel}} = S_1 - S_2 \\;(\\text{Same Dir}), \\quad S_{\\text{rel}} = S_1 + S_2 \\;(\\text{Opposite Dir})',
    plainText: 'Relative Speed = S1 - S2 (Same Direction), S1 + S2 (Opposite Direction)',
    variables: [
      { symbol: 'S1, S2', meaning: 'Speeds of the two moving bodies' },
      { symbol: 'Distance', meaning: 'Sum of lengths of both trains = L1 + L2' },
      { symbol: 'Conversion', meaning: '1 km/h = 5/18 m/s, 1 m/s = 18/5 km/h' },
    ],
    whenToUse: 'Train crossing another train, train passing a moving man or platform.',
    commonTrap: 'Forgetting to convert km/h to m/s when lengths of trains are in meters.',
  },
];
