import { StudyChapter } from '../types';

export const GENERAL_AWARENESS_CHAPTERS: StudyChapter[] = [
  {
    slug: 'indian-polity-constitution',
    title: 'Indian Polity: Constitution, Fundamental Rights & Parliament',
    subject: 'General Awareness',
    unit: 'Unit 3: Indian Polity',
    category: 'Indian Polity',
    subcategory: 'Constitutional Framework',
    priority: 'High Priority',
    tier: 'Tier-I & II',
    estimatedMinutes: 50,
    rulesCount: 15,
    mcqsCount: 35,
    wordCount: 1950,
    summary: 'Making of the Constitution, Preamble, Fundamental Rights (Articles 12–35), DPSPs, President, Parliament, Supreme Court, and High-Yield Articles Table.',
    order: 1,
    nextSlug: 'modern-indian-history',
    favouriteTrap: 'Confusing Fundamental Rights suspended during Emergency (Articles 20 and 21 can NEVER be suspended).',
    memoryTrick: 'FRs: 14-18 Equality, 19-22 Freedom, 23-24 Anti-Exploitation, 25-28 Religion, 29-30 Culture/Education, 32 Constitutional Remedies (Heart & Soul).',
    sections: [
      {
        title: '1. Introduction & Exam Distribution',
        type: 'intro',
        content: 'Indian Polity is the most scoring section of General Awareness in SSC CGL, historically delivering 5 to 7 questions (10 to 14 marks) in Tier-I. The questions are strictly grounded in factual constitutional provisions, articles, schedules, amendments, and institutional jurisdictions.',
      },
      {
        title: '2. Making of the Constitution & Key Timelines',
        type: 'concept',
        content: '• Idea of Constituent Assembly: First proposed by M.N. Roy in 1934; officially demanded by INC in 1935; accepted in principle by British in August Offer (1940); framed under Cabinet Mission Plan (1946).\n• First Meeting: December 9, 1946 (Dr. Sachchidananda Sinha as Temporary President).\n• Permanent President: Dr. Rajendra Prasad elected on December 11, 1946. Vice-President: H.C. Mukherjee.\n• Constitutional Advisor: Sir B.N. Rau.\n• Drafting Committee: Set up on August 29, 1947. Chairman: Dr. B.R. Ambedkar (7 members).\n• Time Taken: 2 Years, 11 Months, 18 Days.\n• Adoption & Enactment: Adopted on November 26, 1949 (celebrated as Constitution Day / Samvidhan Divas). 15 Articles (e.g. Citizenship, Elections) came into force immediately.\n• Full Commencement: January 26, 1950 (celebrated as Republic Day, commemorating Poorna Swaraj resolution of Lahore Session 1929).\n• Original Constitution: Contained Preamble, 395 Articles, 22 Parts, and 8 Schedules. Currently: Over 448 Articles, 25 Parts, and 12 Schedules.',
      },
      {
        title: '3. Fundamental Rights (Part III, Articles 12–35)',
        type: 'rules',
        content: 'Described as the Magna Carta of India. Borrowed from the Bill of Rights (USA). Originally 7 rights; Right to Property (Article 31) was deleted by the 44th Constitutional Amendment Act (1978) and made a legal right under Article 300A in Part XII.',
        table: {
          title: 'The Six Fundamental Rights of Indian Citizens',
          headers: ['Category', 'Article Span', 'Key Constitutional Guarantees'],
          rows: [
            ['Right to Equality', 'Articles 14 – 18', 'Art 14 (Equality before law), Art 15 (No discrimination), Art 16 (Equal opportunity in public employment), Art 17 (Abolition of Untouchability), Art 18 (Abolition of Titles)'],
            ['Right to Freedom', 'Articles 19 – 22', 'Art 19 (Six freedoms: speech, assembly, association, movement, residence, profession), Art 20 (Protection against conviction), Art 21 (Protection of life & personal liberty), Art 21A (Right to education), Art 22 (Protection against arrest)'],
            ['Right against Exploitation', 'Articles 23 – 24', 'Art 23 (Prohibition of human trafficking & forced labour), Art 24 (Prohibition of child labour below 14 years in hazardous industries)'],
            ['Right to Freedom of Religion', 'Articles 25 – 28', 'Art 25 (Freedom of conscience & free profession/practice/propagation), Art 26 (Freedom to manage religious affairs), Art 27 (Freedom from taxation for religion), Art 28 (Freedom from religious instruction in state-aided institutions)'],
            ['Cultural & Educational Rights', 'Articles 29 – 30', 'Art 29 (Protection of language, script & culture of minorities), Art 30 (Right of minorities to establish & administer educational institutions)'],
            ['Right to Constitutional Remedies', 'Article 32', 'Empowers Supreme Court to issue Writs: Habeas Corpus, Mandamus, Prohibition, Certiorari, Quo-Warranto. Called "Heart and Soul of the Constitution" by Dr. B.R. Ambedkar. (High Courts issue writs under Art 226).'],
          ],
        },
      },
      {
        title: '4. Master Table of High-Yield Constitutional Articles for SSC CGL',
        type: 'concept',
        content: 'Direct questions test these article numbers virtually every year:',
        table: {
          title: 'Essential Constitutional Articles Repeated in SSC CGL',
          headers: ['Article', 'Subject Matter', 'High-Yield Exam Note'],
          rows: [
            ['Article 1', 'Name and territory of the Union', '"India, that is Bharat, shall be a Union of States"'],
            ['Article 5-11', 'Citizenship', 'Single citizenship borrowed from Britain; Citizenship Act 1955'],
            ['Article 17', 'Abolition of Untouchability', 'Absolute right; non-derogable'],
            ['Article 21', 'Protection of Life & Liberty', 'Expanded to include Right to Privacy (Puttaswamy case)'],
            ['Article 21A', 'Right to Elementary Education', 'Added by 86th Amendment Act 2002 (age 6 to 14 years)'],
            ['Article 32', 'Writs by Supreme Court', 'Constitutional remedies; Art 226 for High Courts'],
            ['Article 40', 'Organization of Village Panchayats', 'Gandhian Principle of DPSP'],
            ['Article 44', 'Uniform Civil Code', 'Liberal-Intellectual Principle of DPSP; Goa only state originally'],
            ['Article 50', 'Separation of Judiciary from Executive', 'Public services reform principle'],
            ['Article 51A', 'Fundamental Duties', '11 duties in Part IVA; added by 42nd CAA 1976 on Swaran Singh Committee recommendation; 11th added by 86th CAA 2002'],
            ['Article 52', 'President of India', 'Executive head of the Union; Commander-in-Chief of Armed Forces'],
            ['Article 61', 'Procedure for Impeachment of the President', 'Requires 2/3rd majority of total membership of each House; 14 days notice'],
            ['Article 72', 'Pardoning Powers of the President', 'Pardon, commute, remit, respite, reprieve death sentences & court martial'],
            ['Article 76', 'Attorney General of India', 'Highest law officer; right of audience in all courts; can speak in Parliament without voting right'],
            ['Article 108', 'Joint Sitting of Both Houses of Parliament', 'Summoned by President; strictly Presided over by the Speaker of Lok Sabha'],
            ['Article 110', 'Definition of Money Bill', 'Introduced only in Lok Sabha on President recommendation; Speaker certifies; Rajya Sabha has 14 days max'],
            ['Article 112', 'Annual Financial Statement (Budget)', 'Term "Budget" is NOT used in the Constitution'],
            ['Article 123', 'Ordinance-making power of the President', 'Max validity: 6 months and 6 weeks'],
            ['Article 148', 'Comptroller & Auditor General (CAG)', 'Guardian of public purse; term 6 years or 65 years age'],
            ['Article 280', 'Finance Commission', 'Constituted every 5 years by President (1 Chairman + 4 Members)'],
            ['Article 324', 'Election Commission of India', 'Superintendence, direction and control of elections'],
            ['Article 352', 'National Emergency', 'War, external aggression, or armed rebellion'],
            ['Article 356', 'President’s Rule (State Emergency)', 'Breakdown of constitutional machinery in a State'],
            ['Article 360', 'Financial Emergency', 'Never declared in India so far'],
            ['Article 368', 'Power of Parliament to amend the Constitution', 'Part XX; special majority required'],
          ],
        },
      },
      {
        title: '5. Major Constitutional Amendments Table',
        type: 'concept',
        content: 'Landmark constitutional amendments frequently tested in SSC CGL:',
        table: {
          title: 'Chronology of Landmark Constitutional Amendments',
          headers: ['Amendment', 'Year', 'Key Significance'],
          rows: [
            ['1st CAA', '1951', 'Added Ninth Schedule to protect land reform laws from judicial review; inserted restrictions on speech.'],
            ['7th CAA', '1956', 'Reorganized states on linguistic basis (14 States & 6 UTs); abolished Class A, B, C, D states.'],
            ['42nd CAA', '1976', '"Mini Constitution"; added Socialist, Secular, Integrity to Preamble; added Fundamental Duties (Part IVA); added Art 39A, 43A, 48A.'],
            ['44th CAA', '1978', 'Removed Right to Property from FRs; substituted "internal disturbance" with "armed rebellion" in Art 352; guaranteed Art 20 & 21 cannot be suspended during emergency.'],
            ['52nd CAA', '1985', 'Anti-Defection Law; added Tenth Schedule to prevent floor-crossing.'],
            ['61st CAA', '1989', 'Lowered voting age from 21 years to 18 years for Lok Sabha and State Legislative Assemblies (Art 326).'],
            ['73rd CAA', '1992', 'Granted constitutional status to Panchayati Raj Institutions; added Part IX and Eleventh Schedule (29 functional items).'],
            ['74th CAA', '1992', 'Constitutional status to Urban Local Bodies (Municipalities); added Part IXA and Twelfth Schedule (18 functional items).'],
            ['86th CAA', '2002', 'Made education a Fundamental Right (Art 21A); amended Art 45; added 11th Fundamental Duty under Art 51A(k).'],
            ['101st CAA', '2016', 'Introduced Goods and Services Tax (GST); inserted Art 246A, 269A, and 279A (GST Council).'],
            ['103rd CAA', '2019', '10% Reservation for Economically Weaker Sections (EWS) in education and public employment (amended Art 15 & 16).'],
            ['106th CAA', '2023', 'Nari Shakti Vandan Adhiniyam: 33% reservation for women in Lok Sabha and State Legislative Assemblies.'],
          ],
        },
      },
      {
        title: '6. Solved Questions (SSC CGL Standard)',
        type: 'examples',
        content: 'Authentic examination format questions with conceptual explanation.',
        solvedExamples: [
          {
            level: 'Moderate',
            question: 'Which of the following Articles of the Constitution of India guarantees that no person shall be deprived of his life or personal liberty except according to procedure established by law?\n(A) Article 19  (B) Article 20  (C) Article 21  (D) Article 22',
            solution: 'Article 21 declares: "No person shall be deprived of his life or personal liberty except according to procedure established by law." The Supreme Court in the landmark Maneka Gandhi case (1978) held that this procedure must be "just, fair and reasonable", establishing the American concept of Due Process of Law in India.\nCorrect Answer: (C)',
            fastTrick: 'Art 21 is the foundational right to life and liberty.',
          },
          {
            level: 'SSC-level',
            question: 'Who among the following presides over a joint sitting of both Houses of Parliament in India?\n(A) The President of India\n(B) The Vice-President of India (Chairman of Rajya Sabha)\n(C) The Prime Minister of India\n(D) The Speaker of Lok Sabha',
            solution: 'Under Article 108, the President of India SUMMONS the joint sitting to resolve deadlocks on Ordinary Bills. However, under Article 118(4), the joint sitting is STRICTLY PRESIDED over by the Speaker of the Lok Sabha. If the Speaker is absent, the Deputy Speaker presides; if both are absent, the Deputy Chairman of Rajya Sabha presides. The Chairman of Rajya Sabha (Vice President) NEVER presides over a joint sitting because he is not a member of either House.\nCorrect Answer: (D)',
            fastTrick: 'President summons; Speaker presides. Vice President never presides.',
            trapNote: 'Candidates often pick the Vice-President / Chairman of Rajya Sabha.',
          },
        ],
      },
      {
        title: '7. Chapter Practice Questions',
        type: 'practice',
        content: 'Test your retention of articles and amendments.',
        practiceQuestions: [
          {
            id: 'pol-p-1',
            question: 'Under which Article of the Constitution can the President of India seek the advisory opinion of the Supreme Court?',
            options: ['Article 129', 'Article 136', 'Article 143', 'Article 148'],
            correctIndex: 2,
            explanation: 'Article 143 confers advisory jurisdiction upon the Supreme Court, permitting the President to refer questions of law or fact of public importance. The advice tendered is not binding on the President.',
            sourceType: 'PYQ-style',
          },
          {
            id: 'pol-p-2',
            question: 'The Fundamental Duties were incorporated into the Constitution of India upon the recommendation of which committee?',
            options: ['Sarkaria Commission', 'Swaran Singh Committee', 'Balwant Rai Mehta Committee', 'Verma Committee'],
            correctIndex: 1,
            explanation: 'The Swaran Singh Committee (1976) recommended the inclusion of Fundamental Duties, leading to the 42nd Constitutional Amendment Act 1976 inserting Part IVA and Article 51A.',
            sourceType: 'PYQ-style',
          },
        ],
      },
      {
        title: '8. Quick Revision: What You Must Remember',
        type: 'revision',
        content: '• Preamble keywords order: Sovereign, Socialist, Secular, Democratic, Republic.\n• Fundamental Rights cannot be suspended in Articles 20 & 21 even during National Emergency.\n• Money Bill (Art 110) cannot be introduced in Rajya Sabha; Rajya Sabha has only 14 days delay power.\n• Speaker decides whether a bill is a Money Bill; decision is final.\n• 61st Amendment lowered voting age from 21 to 18.\n• 73rd & 74th Amendments gave constitutional status to Panchayats (Part IX) and Municipalities (Part IXA).',
      },
    ],
  },
  {
    slug: 'modern-indian-history',
    title: 'Modern Indian History: Freedom Movement & Chronology',
    subject: 'General Awareness',
    unit: 'Unit 1: Indian History',
    category: 'Indian History',
    subcategory: 'Modern History & Freedom Struggle',
    priority: 'High Priority',
    tier: 'Tier-I & II',
    estimatedMinutes: 45,
    rulesCount: 12,
    mcqsCount: 30,
    wordCount: 1800,
    summary: 'European arrivals, Revolt of 1857, Governor-Generals, Indian National Congress sessions, Gandhian Mass Movements, and Chronology Table (1857–1947).',
    order: 2,
    nextSlug: 'physical-indian-geography',
    favouriteTrap: 'Confusing the chronological order of: Non-Cooperation Movement (1920), Simon Commission (1927), Civil Disobedience (1930), and Quit India (1942).',
    memoryTrick: 'Gandhian triad: Champaran (1917) → Ahmedabad Mill (1918) → Kheda (1918) = CAK (First hunger strike was Ahmedabad).',
    sections: [
      {
        title: '1. Introduction & Historical Scope',
        type: 'intro',
        content: 'Modern Indian History is the highest yielding history module in SSC CGL. Questions concentrate heavily on the Freedom Struggle between 1857 and 1947, important Governor-Generals and Viceroys, socio-religious reform leaders, and landmark sessions of the Indian National Congress.',
      },
      {
        title: '2. Chronology of European Arrival & British Dominance',
        type: 'concept',
        content: '• Order of European Arrivals: Portuguese (1498, Vasco da Gama at Calicut) → Dutch (1605) → English (1608, Captain William Hawkins at Jahangir’s court) → Danish (1620) → French (1664).\n• Battle of Plassey (June 23, 1757): Robert Clive defeated Nawab Siraj-ud-Daulah of Bengal with the betrayal of Mir Jafar. Marked foundation of British political rule in India.\n• Battle of Buxar (October 22, 1764): Hector Munro defeated joint forces of Mir Qasim (Bengal), Shuja-ud-Daulah (Awadh), and Mughal Emperor Shah Alam II. Led to Treaty of Allahabad (1765) granting Diwani rights (tax collection) of Bengal, Bihar, and Orissa to the Company.',
      },
      {
        title: '3. Master Chronology Table of Indian National Movement (1857–1947)',
        type: 'concept',
        content: 'Every date in this table has been tested multiple times by SSC:',
        table: {
          title: 'Chronology of the Indian Freedom Struggle',
          headers: ['Year', 'Historic Milestone / Event', 'Key Figures & Significance'],
          rows: [
            ['1857', 'Revolt of 1857 (Sepoy Mutiny)', 'Began at Meerut (May 10). Mangal Pandey at Barrackpore (March 29). Bahadur Shah Zafar declared Emperor. Lord Canning was Governor-General.'],
            ['1858', 'Government of India Act 1858', 'East India Company rule ended; direct Crown rule began. Governor-General designated Viceroy (Lord Canning first Viceroy).'],
            ['1885', 'Foundation of Indian National Congress (INC)', 'Founded at Gokuldas Tejpal Sanskrit College, Bombay (Dec 28) by A.O. Hume. 72 delegates attended. First President: W.C. Bonnerjee. Viceroy: Lord Dufferin.'],
            ['1905', 'Partition of Bengal & Swadeshi Movement', 'Announced by Lord Curzon. Triggered Swadeshi & Boycott Movement; Vande Mataram became national anthem of protest.'],
            ['1906', 'Foundation of All-India Muslim League', 'Founded at Dhaka by Nawab Salimullah, Aga Khan, and Mohsin-ul-Mulk.'],
            ['1907', 'Surat Split of Congress', 'INC split into Moderates (Gokhale) and Extremists (Tilak, Lal-Bal-Pal). Rash Behari Ghosh presided.'],
            ['1909', 'Morley-Minto Reforms (Indian Councils Act)', 'Introduced Separate Electorates for Muslims (Father of Communal Electorate: Lord Minto).'],
            ['1911', 'Delhi Durbar', 'Partition of Bengal annulled; capital shifted from Calcutta to Delhi by Lord Hardinge II.'],
            ['1915', 'Return of Mahatma Gandhi', 'Gandhi returned from South Africa on January 9, 1915 (commemorated as Pravasi Bharatiya Divas).'],
            ['1916', 'Lucknow Pact & Home Rule League', 'Reunion of Moderates & Extremists; joint pact between INC and Muslim League. Tilak and Annie Besant launched Home Rule Leagues.'],
            ['1919', 'Rowlatt Act & Jallianwala Bagh Massacre', 'Rowlatt Act passed (Black Act). Jallianwala Bagh massacre (April 13, Baisakhi day) ordered by General Reginald Dyer. Rabindranath Tagore renounced Knighthood.'],
            ['1920', 'Non-Cooperation & Khilafat Movement', 'Launched by Mahatma Gandhi with Ali Brothers (Shaukat & Mohammad Ali). Surrender of titles and boycott of schools/courts.'],
            ['1922', 'Chauri Chaura Incident', 'Violence at Chauri Chaura (Gorakhpur, Feb 4); 22 policemen killed. Gandhi abruptly called off Non-Cooperation Movement.'],
            ['1923', 'Formation of Swaraj Party', 'Formed by C.R. Das (President) and Motilal Nehru (Secretary) to enter legislative councils.'],
            ['1927-28', 'Simon Commission Arrival & Boycott', 'All-white commission headed by Sir John Simon. Lala Lajpat Rai died from lathi charge during Lahore protest (Nov 1928).'],
            ['1929', 'Lahore Session & Poorna Swaraj', 'Presided over by Jawaharlal Nehru. Passed "Poorna Swaraj" (Complete Independence) resolution. Tricolour hoisted on banks of Ravi River.'],
            ['1930', 'Dandi March & Civil Disobedience Movement', 'Dandi Salt March (March 12 – April 6): Gandhi walked 240 miles from Sabarmati to Dandi with 78 followers to break the Salt Law.'],
            ['1931', 'Gandhi-Irwin Pact & Karachi Session', 'Signed on March 5; suspended Civil Disobedience; Gandhi agreed to attend 2nd Round Table Conference. Bhagat Singh, Sukhdev, and Rajguru executed on March 23, 1931.'],
            ['1932', 'Poona Pact', 'Agreement between Mahatma Gandhi (fasting in Yerwada Jail) and Dr. B.R. Ambedkar; replaced separate electorates for depressed classes with reserved seats.'],
            ['1942', 'Quit India Movement', 'Launched at Gowalia Tank Maidan, Bombay (August 8). Gandhi gave call: "Do or Die" (Karo ya Maro). All top leaders arrested under Operation Zero Hour.'],
            ['1946', 'Cabinet Mission Plan & Naval Mutiny', 'Royal Indian Navy (RIN) Mutiny (Feb 1946). Cabinet Mission (Pethick-Lawrence, Stafford Cripps, A.V. Alexander) proposed Constituent Assembly.'],
            ['1947', 'Mountbatten Plan & Independence', '3rd June Plan for Partition. Indian Independence Act 1947 passed by British Parliament. India gained independence on August 15, 1947.'],
          ],
        },
      },
      {
        title: '4. Solved Examples (SSC CGL Standard)',
        type: 'examples',
        content: 'Historical questions solved with exact context.',
        solvedExamples: [
          {
            level: 'Moderate',
            question: 'During whose tenure as Viceroy was the capital of British India shifted from Calcutta to Delhi in 1911?\n(A) Lord Curzon  (B) Lord Hardinge II  (C) Lord Minto  (D) Lord Chelmsford',
            solution: 'At the grand Delhi Durbar of December 1911 attended by King George V and Queen Mary, two major announcements were made: 1) The annulment of the Partition of Bengal, and 2) The transfer of the imperial capital from Calcutta to Delhi. The Viceroy of India at that time was Lord Hardinge II (who was later targeted in the Delhi Conspiracy Case / Chandni Chowk bomb attack by Rash Behari Bose in 1912).\nCorrect Answer: (B)',
            fastTrick: '1911 Delhi Durbar = Lord Hardinge II.',
          },
        ],
      },
      {
        title: '5. Practice Questions',
        type: 'practice',
        content: 'Test your chronological accuracy.',
        practiceQuestions: [
          {
            id: 'his-p-1',
            question: 'Arrange the following events in correct chronological order:\n1. Dandi March\n2. Chauri Chaura Incident\n3. Simon Commission Arrival\n4. Lucknow Pact',
            options: ['4, 2, 3, 1', '2, 4, 3, 1', '4, 3, 2, 1', '1, 2, 3, 4'],
            correctIndex: 0,
            explanation: 'Lucknow Pact (1916) → Chauri Chaura Incident (1922) → Simon Commission Arrival (1928) → Dandi March (1930). Correct sequence: 4, 2, 3, 1.',
            sourceType: 'PYQ-style',
          },
        ],
      },
      {
        title: '6. Quick Revision: What You Must Remember',
        type: 'revision',
        content: '• First President of INC: W.C. Bonnerjee (Bombay, 1885).\n• First Woman President of INC: Annie Besant (Calcutta, 1917).\n• First Indian Woman President of INC: Sarojini Naidu (Kanpur, 1925).\n• Only Session presided by Mahatma Gandhi: Belgaum (1924).\n• Subhash Chandra Bose presided over: Haripura (1938) and Tripuri (1939).\n• Swaraj Party founded by: C.R. Das and Motilal Nehru (1923).',
      },
    ],
  },
  {
    slug: 'physical-indian-geography',
    title: 'Geography: Physical, Indian Drainage & Climate',
    subject: 'General Awareness',
    unit: 'Unit 2: Geography',
    category: 'Geography',
    subcategory: 'Physical & Indian Geography',
    priority: 'High Priority',
    tier: 'Tier-I & II',
    estimatedMinutes: 45,
    rulesCount: 10,
    mcqsCount: 30,
    wordCount: 1750,
    summary: 'Atmospheric layers, ocean currents, Himalayan vs Peninsular drainage systems, major dams, monsoon mechanism, and soils of India.',
    order: 3,
    nextSlug: 'indian-economy-banking',
    favouriteTrap: 'Confusing West-flowing rivers (Narmada, Tapi flowing into Arabian Sea through rift valleys) with East-flowing rivers (Godavari, Krishna, Mahanadi creating deltas).',
    memoryTrick: 'West flowing rivers into Arabian Sea: "NaMaSTE SL" (Narmada, Mahi, Sabarmati, Tapi, Sharavati, Luni). They do NOT form deltas; they form estuaries.',
    sections: [
      {
        title: '1. Introduction & Exam Scope',
        type: 'intro',
        content: 'Geography in SSC CGL consistently delivers 4 to 5 questions in Tier-I. The exam strongly emphasizes Indian Drainage Systems (tributaries, origins, multipurpose dams), physical divisions of the Himalayas, Monsoon mechanics, Soil types, and atmospheric strata.',
      },
      {
        title: '2. Atmospheric Strata & Properties Table',
        type: 'concept',
        content: 'The atmosphere is divided into five concentric thermal layers:',
        table: {
          title: 'Structure of the Earth’s Atmosphere',
          headers: ['Layer', 'Altitude Span', 'Physical Phenomena & Exam Highlights'],
          rows: [
            ['Troposphere', '0 to 18 km (8 km at poles, 18 km at equator)', 'Contains 75% of atmospheric mass; ALL weather phenomena (clouds, rain, storms, lightning) occur here; temperature drops with height (Normal Lapse Rate: 6.5°C per km).'],
            ['Stratosphere', 'Up to 50 km', 'Contains the OZONE LAYER (O3) which absorbs lethal solar UV radiation; free from clouds and violent air turbulence, making it IDEAL FOR FLYING JET AIRCRAFT.'],
            ['Mesosphere', '50 to 80 km', 'Coldest layer of atmosphere (temperatures drop to -100°C); METEORS BURN UP in this layer upon atmospheric entry.'],
            ['Thermosphere (Ionosphere)', '80 to 400 km', 'Contains electrically charged ions; reflects radio waves back to Earth, enabling LONG-DISTANCE RADIO COMMUNICATION; Auroras (Borealis & Australis) occur here.'],
            ['Exosphere', 'Above 400 km', 'Outermost layer grading into interplanetary space; contains extremely light gases like Hydrogen and Helium; geostationary satellites orbit here.'],
          ],
        },
      },
      {
        title: '3. Indian River Systems: Himalayan vs Peninsular Rivers',
        type: 'rules',
        content: 'Comprehensive classification of Indian drainage systems:',
        table: {
          title: 'Himalayan Rivers vs Peninsular Rivers',
          headers: ['Feature', 'Himalayan Rivers (Indus, Ganga, Brahmaputra)', 'Peninsular Rivers (Godavari, Krishna, Narmada, Tapi)'],
          rows: [
            ['Nature of Flow', 'Perennial (Fed by both melting snow/glaciers and rainfall)', 'Seasonal / Non-perennial (Fed solely by monsoon rainfall)'],
            ['Age & Profile', 'Young, active rivers with deep V-shaped valleys and gorges', 'Old, mature rivers with broad, shallow, graded valleys'],
            ['Course Dynamics', 'Long courses, dynamic meanders, shifting riverbeds', 'Fixed, rigid courses through fault lines and plateau rocks'],
            ['Coast Destination', 'All discharge into the Bay of Bengal (Indus into Arabian Sea)', 'East-flowing discharge into Bay of Bengal; West-flowing into Arabian Sea'],
            ['Estuary vs Delta', 'Form enormous world deltas (Sundarbans Delta)', 'East-flowing form deltas; West-flowing (Narmada, Tapi) form ESTUARIES without deltas'],
          ],
        },
      },
      {
        title: '4. Major Indian Rivers, Origins & Multipurpose River Dams Table',
        type: 'concept',
        content: 'High-frequency SSC pairings of rivers, origin locations, and dams:',
        table: {
          title: 'Important Rivers, Origins and Major Multipurpose Dams',
          headers: ['River', 'Origin / Source', 'Major Multipurpose Dam Project', 'Key Tributaries'],
          rows: [
            ['Indus', 'Bokhar Chu glacier near Lake Manasarovar (Tibet)', 'Tarbela Dam (Pakistan); Nimoo Bazgo (Ladakh)', 'Jhelum, Chenab (largest), Ravi, Beas, Sutlej'],
            ['Ganga', 'Gangotri Glacier (Bhagirathi meets Alaknanda at Devprayag)', 'Tehri Dam (Bhagirathi, Highest in India); Farakka Barrage', 'Yamuna (longest right-bank), Ramganga, Gomti, Ghaghara, Gandak, Kosi, Son'],
            ['Brahmaputra', 'Chemayungdung Glacier (Tibet, called Tsangpo)', 'Dhubri-Sadiya bridge; Bogibeel bridge', 'Subansiri, Dibang, Lohit, Teesta, Manas'],
            ['Godavari', 'Trimbakeshwar near Nashik (Maharashtra)', 'Pochampad (Sri Ram Sagar); Polavaram Project', 'Largest Peninsular river ("Dakshin Ganga"); Penganga, Wainganga, Indravati, Manjira'],
            ['Krishna', 'Mahabaleshwar (Maharashtra)', 'Nagarjuna Sagar Dam; Almatti Dam; Srisailam Dam', 'Tungabhadra (largest), Bhima, Koyna, Ghataprabha, Malaprabha'],
            ['Kaveri', 'Talakaveri in Brahmagiri Hills (Karnataka)', 'Mettur Dam (Tamil Nadu); Krishna Raja Sagara (KRS)', 'Known as "Ganga of the South"; Hemavati, Shimsha, Arkavathi, Kabini, Bhavani'],
            ['Narmada', 'Amarkantak Plateau (Madhya Pradesh)', 'Sardar Sarovar Dam (Gujarat); Indira Sagar Dam', 'Flows through rift valley between Vindhyas & Satpuras; Dhuandhar Falls (Jabalpur)'],
            ['Mahanadi', 'Sihawa in Dhamtari (Chhattisgarh)', 'Hirakud Dam (Odisha, Longest earthen dam in India)', 'Seonath, Hasdeo, Mand, Ib, Jonk, Tel'],
          ],
        },
      },
      {
        title: '5. Solved Examples',
        type: 'examples',
        content: 'Geography questions solved with geological context.',
        solvedExamples: [
          {
            level: 'Moderate',
            question: 'At which of the following confluence points do the rivers Bhagirathi and Alaknanda unite to form the river Ganga?\n(A) Rudraprayag  (B) Karnaprayag  (C) Devprayag  (D) Vishnuprayag',
            solution: 'The Panch Prayag of Uttarakhand are:\n1. Vishnuprayag: Dhauliganga meets Alaknanda.\n2. Nandaprayag: Nandakini meets Alaknanda.\n3. Karnaprayag: Pindar meets Alaknanda.\n4. Rudraprayag: Mandakini meets Alaknanda.\n5. Devprayag: Bhagirathi meets Alaknanda to officially form the river GANGA.\nCorrect Answer: (C)',
            fastTrick: 'B + A = Devprayag (BAD: Bhagirathi + Alaknanda = Devprayag).',
          },
        ],
      },
      {
        title: '6. Practice Questions',
        type: 'practice',
        content: 'Practice river and climate questions.',
        practiceQuestions: [
          {
            id: 'geo-p-1',
            question: 'Which is the only river in India that crosses the Tropic of Cancer twice?',
            options: ['Mahi', 'Narmada', 'Tapi', 'Sabarmati'],
            correctIndex: 0,
            explanation: 'The Mahi River originates in the Vindhya range of Madhya Pradesh, enters Rajasthan, and then turns south into Gujarat, crossing the Tropic of Cancer (23.5° N) twice before emptying into the Gulf of Khambhat.',
            sourceType: 'PYQ-style',
          },
        ],
      },
      {
        title: '7. Quick Revision: What You Must Remember',
        type: 'revision',
        content: '• Highest Dam in India: Tehri Dam (Bhagirathi river, Uttarakhand, 260.5 m).\n• Longest Dam in India: Hirakud Dam (Mahanadi river, Odisha, 25.8 km).\n• Narmada and Tapi flow through rift valleys into the Arabian Sea forming estuaries (no deltas).\n• Majuli in Assam (Brahmaputra river) is the largest inhabited riverine island in the world.\n• Standard Meridian of India: 82°30\' E longitude (Mirzapur, UP), ahead of GMT by +5 hours 30 mins.',
      },
    ],
  },
  {
    slug: 'general-science-physics-chemistry-biology',
    title: 'General Science: Physics, Chemistry & Biology Essentials',
    subject: 'General Awareness',
    unit: 'Unit 5: General Science',
    category: 'General Science',
    subcategory: 'Physics, Chemistry & Biology',
    priority: 'High Priority',
    tier: 'Tier-I & II',
    estimatedMinutes: 50,
    rulesCount: 16,
    mcqsCount: 35,
    wordCount: 1900,
    summary: 'SI Units & dimensions, Newton’s laws, optics & mirrors, Periodic Table trends, chemical formulas & everyday compounds, vitamins & deficiency diseases, and human organ systems.',
    order: 4,
    favouriteTrap: 'Confusing concave mirrors (used by dentists and in car headlights for converging light) with convex mirrors (used as rear-view mirrors for wide-angle erect diminished views).',
    memoryTrick: 'Vitamins solubility: Water Soluble = B & C ("WBC"); Fat Soluble = K, E, D, A ("KEDA").',
    sections: [
      {
        title: '1. Introduction & Science Weightage',
        type: 'intro',
        content: 'General Science delivers 6 to 8 questions (12 to 16 marks) in SSC CGL Tier-I, divided across Biology (largest share, 3–4 questions), Chemistry (2–3 questions), and Physics (2 questions). Questions are strictly application-oriented, focusing on everyday scientific principles, vitamins, human diseases, chemical names of household substances, and SI units.',
      },
      {
        title: '2. Physics: Fundamental SI Units & Physical Quantities Table',
        type: 'concept',
        content: 'Memorize these high-frequency SI units and derived physical parameters:',
        table: {
          title: 'Essential SI Units Tested in SSC CGL',
          headers: ['Physical Quantity', 'SI Unit', 'Symbol', 'Dimensional Formula / Derived Expression'],
          rows: [
            ['Electric Current', 'Ampere', 'A', 'Fundamental Base Unit'],
            ['Luminous Intensity', 'Candela', 'cd', 'Fundamental Base Unit'],
            ['Force / Weight', 'Newton', 'N', 'kg·m/s² [M¹L¹T⁻²]'],
            ['Work / Energy / Heat', 'Joule', 'J', 'N·m = kg·m²/s² [M¹L²T⁻²]'],
            ['Power', 'Watt', 'W', 'Joule/second (1 Horsepower = 746 Watts)'],
            ['Pressure / Stress', 'Pascal', 'Pa', 'Newton/m² (1 bar = 10⁵ Pa; 1 atm = 101,325 Pa)'],
            ['Frequency', 'Hertz', 'Hz', 's⁻¹ (cycles per second)'],
            ['Electric Charge', 'Coulomb', 'C', 'Ampere·second (A·s)'],
            ['Potential Difference (Voltage)', 'Volt', 'V', 'Joule/Coulomb (W/A)'],
            ['Electrical Resistance', 'Ohm', 'Ω', 'Volt/Ampere (V/A)'],
            ['Electrical Conductance', 'Siemens', 'S', 'Ohm⁻¹ (mho)'],
            ['Magnetic Flux', 'Weber', 'Wb', 'Volt·second'],
            ['Magnetic Flux Density', 'Tesla', 'T', 'Weber/m²'],
            ['Radioactivity', 'Becquerel', 'Bq', 'Disintegrations per second (Historical unit: Curie)'],
          ],
        },
      },
      {
        title: '3. Chemistry: Common Household Chemical Names & Formulas Table',
        type: 'concept',
        content: 'SSC repeatedly tests common names and chemical identities of household and industrial compounds:',
        table: {
          title: 'Everyday Chemical Compounds & SSC High-Yield Formulas',
          headers: ['Common Name', 'Chemical Name', 'Chemical Formula', 'Key Industrial / Domestic Use'],
          rows: [
            ['Baking Soda', 'Sodium Hydrogen Carbonate', 'NaHCO3', 'Antacid, baking powder, fire extinguishers'],
            ['Washing Soda', 'Sodium Carbonate Decahydrate', 'Na2CO3 · 10H2O', 'Glass, soap, paper industries; removing permanent hardness of water'],
            ['Bleaching Powder', 'Calcium Oxychloride', 'CaOCl2', 'Disinfectant for drinking water; bleaching agent in textile industry'],
            ['Plaster of Paris (POP)', 'Calcium Sulphate Hemihydrate', 'CaSO4 · 1/2 H2O', 'Setting fractured bones; making statues, casts, and false ceilings'],
            ['Gypsum', 'Calcium Sulphate Dihydrate', 'CaSO4 · 2H2O', 'Added to cement to retard its setting time (POP heated to 373 K yields POP)'],
            ['Slaked Lime', 'Calcium Hydroxide', 'Ca(OH)2', 'White washing walls; reacts with CO2 to form shiny CaCO3 layer'],
            ['Quick Lime', 'Calcium Oxide', 'CaO', 'Manufacturing cement; drying agent'],
            ['Caustic Soda', 'Sodium Hydroxide', 'NaOH', 'Manufacturing soaps, detergents, and synthetic fibers'],
            ['Laughing Gas', 'Nitrous Oxide', 'N2O', 'Anesthetic and propellant gas'],
            ['Tear Gas', 'Chloropicrin', 'CCl3NO2', 'Riot control agent'],
            ['Dry Ice', 'Solid Carbon Dioxide', 'CO2 (Solid)', 'Cryogenic refrigerant; sublimes directly from solid to gas at -78.5°C'],
            ['Blue Vitriol', 'Copper Sulphate Pentahydrate', 'CuSO4 · 5H2O', 'Fungicide; electroplating; deep blue crystalline solid'],
            ['Green Vitriol', 'Ferrous Sulphate Heptahydrate', 'FeSO4 · 7H2O', 'Iron supplements and dye manufacturing'],
          ],
        },
      },
      {
        title: '4. Biology: Complete Vitamins, Deficiencies & Chemical Names Table',
        type: 'concept',
        content: 'The definitive vitamins reference table for SSC CGL:',
        table: {
          title: 'Vitamins, Chemical Names, Deficiency Diseases & Sources',
          headers: ['Vitamin', 'Chemical Name', 'Deficiency Disease', 'Rich Dietary Sources'],
          rows: [
            ['Vitamin A', 'Retinol', 'Night Blindness (Nyctalopia), Xerophthalmia (dry cornea)', 'Carrots, mangoes, papaya, milk, fish liver oil'],
            ['Vitamin B1', 'Thiamine', 'Beri-Beri (weak muscles, nerve degeneration)', 'Unpolished rice, yeast, eggs, pulses'],
            ['Vitamin B2', 'Riboflavin', 'Cheilosis (cracked lips & mouth corners), Glossitis', 'Milk, eggs, liver, green leafy vegetables'],
            ['Vitamin B3', 'Niacin / Nicotinic Acid', 'Pellagra (4D symptoms: Dermatitis, Diarrhea, Dementia, Death)', 'Meat, fish, peanuts, whole wheat'],
            ['Vitamin B5', 'Pantothenic Acid', 'Paresthesia (burning feet syndrome)', 'Mushrooms, avocado, eggs, meat'],
            ['Vitamin B6', 'Pyridoxine', 'Anemia, convulsions, skin disorders', 'Fish, liver, meat, bananas'],
            ['Vitamin B7', 'Biotin', 'Hair loss, dermatitis, nervous symptoms', 'Egg yolk, liver, nuts'],
            ['Vitamin B9', 'Folic Acid', 'Megaloblastic Anemia, neural tube defects in fetus', 'Spinach, citrus fruits, lentils'],
            ['Vitamin B12', 'Cyanocobalamin', 'Pernicious Anemia (contains COBALT metal)', 'Meat, fish, dairy (NOT found in plant foods)'],
            ['Vitamin C', 'Ascorbic Acid', 'Scurvy (bleeding gums, delayed wound healing)', 'Amla (richest), lemon, oranges, guava (destroyed by heat)'],
            ['Vitamin D', 'Calciferol', 'Rickets (in children, bowed legs), Osteomalacia (in adults)', 'Sunlight synthesis, cod liver oil, fortified milk'],
            ['Vitamin E', 'Tocopherol', 'Infertility/Sterility, muscular weakness ("Beauty Vitamin")', 'Wheat germ oil, almonds, sunflower seeds'],
            ['Vitamin K', 'Phylloquinone', 'Defective blood clotting (excessive hemorrhaging)', 'Green leafy vegetables, cabbage (synthesized by gut bacteria)'],
          ],
        },
      },
      {
        title: '5. Solved Examples (SSC CGL Standard)',
        type: 'examples',
        content: 'Worked problems from official exam patterns.',
        solvedExamples: [
          {
            level: 'Moderate',
            question: 'Which vitamin contains a metal atom in its complex chemical structure, and what is that metal?\n(A) Vitamin B6; Zinc\n(B) Vitamin B12; Cobalt\n(C) Vitamin C; Copper\n(D) Vitamin A; Iron',
            solution: 'Vitamin B12 is chemically named Cyanocobalamin because its central coordination complex contains a trivalent Cobalt (Co) ion. It is essential for red blood cell maturation and myelin sheath maintenance. Plant foods do not naturally synthesize Vitamin B12; humans acquire it from animal foods or gut bacterial synthesis.\nCorrect Answer: (B)',
            fastTrick: 'Cyanocobalamin = Contains Cobalt.',
          },
          {
            level: 'Moderate',
            question: 'Why is a convex mirror preferred as a rear-view (wing) mirror in motor vehicles?\n(A) It produces an inverted magnified image\n(B) It produces a real erect image\n(C) It always forms a virtual, erect and diminished image providing a wide field of view\n(D) It absorbs high glare',
            solution: 'A convex mirror always forms a virtual, erect, and diminished (smaller) image irrespective of the object’s distance. Because the mirror curves outwards, it diverges light rays and provides a vastly wider field of view compared to a plane or concave mirror, enabling the driver to monitor traffic behind safely.\nCorrect Answer: (C)',
            fastTrick: 'Convex mirror = Erect + Diminished + Wide field of view.',
          },
        ],
      },
      {
        title: '6. Practice Questions',
        type: 'practice',
        content: 'Check your science concepts.',
        practiceQuestions: [
          {
            id: 'sci-p-1',
            question: 'Which chemical compound is responsible for the permanent hardness of water?',
            options: [
              'Chlorides and sulphates of Calcium and Magnesium',
              'Bicarbonates of Calcium and Magnesium',
              'Carbonates of Sodium and Potassium',
              'Nitrates of Iron',
            ],
            correctIndex: 0,
            explanation: 'Temporary hardness is caused by dissolved Bicarbonates of Calcium and Magnesium (removable by boiling). Permanent hardness is caused by dissolved Chlorides and Sulphates of Calcium and Magnesium (CaCl2, MgCl2, CaSO4, MgSO4), which cannot be removed by boiling and requires washing soda or ion-exchange resins.',
            sourceType: 'PYQ-style',
          },
        ],
      },
      {
        title: '7. Quick Revision: What You Must Remember',
        type: 'revision',
        content: '• Water soluble vitamins: B-complex and C. Fat soluble vitamins: K, E, D, A.\n• Plaster of Paris formula: CaSO4 · 1/2 H2O. Gypsum formula: CaSO4 · 2H2O.\n• Bleaching powder formula: CaOCl2.\n• Dentists mirror & car headlights: Concave Mirror (converging).\n• Vehicle rear-view mirror: Convex Mirror (diverging, wide field of view).\n• Cobalt metal is present in Vitamin B12 (Cyanocobalamin).\n• Power of lens = 1 / focal length (in meters), measured in Dioptres (D).',
      },
    ],
  },
];
