import { GrammarRuleItem } from '../types';

export const GRAMMAR_RULES: GrammarRuleItem[] = [
  {
    id: 'rule-sva-1',
    ruleNumber: 1,
    title: 'Prepositional Phrase Interposition',
    topic: 'Subject–Verb Agreement',
    category: 'Grammar Foundation',
    statement: 'The verb must always agree with the true head subject noun, NOT with the noun inside an intervening prepositional phrase.',
    incorrectExample: 'The quality of these mangoes were not up to the mark.',
    correctExample: 'The quality of these mangoes was not up to the mark.',
    explanation: 'The head noun is "quality" (singular uncountable). The plural noun "mangoes" is an object of the preposition "of" and cannot dictate the verb form.',
    frequentExamTrap: 'TCS places long plural prepositional phrases directly before the verb to create proximity illusion.',
  },
  {
    id: 'rule-sva-2',
    ruleNumber: 2,
    title: 'Compound Subject with "As well as", "Along with", "Together with"',
    topic: 'Subject–Verb Agreement',
    category: 'Grammar Foundation',
    statement: 'When two subjects are joined by "as well as", "along with", "together with", "in addition to", "accompanied by", or "with", the verb strictly follows the FIRST subject.',
    incorrectExample: 'The captain along with his team members were felicitated by the Governor.',
    correctExample: 'The captain along with his team members was felicitated by the Governor.',
    explanation: '"along with his team members" is a parenthetical adjunct. The true grammatical subject is "The captain" (singular).',
    frequentExamTrap: 'Do not treat "along with" as an equivalent of "and". It does not create a plural compound subject.',
  },
  {
    id: 'rule-sva-3',
    ruleNumber: 3,
    title: 'Correlative Proximity Concord ("Neither...nor", "Either...or")',
    topic: 'Subject–Verb Agreement',
    category: 'Grammar Foundation',
    statement: 'When subjects are connected by "either...or", "neither...nor", or "not only...but also", the verb must agree with the subject closest to it in position.',
    incorrectExample: 'Neither the teacher nor the students was present in the auditorium.',
    correctExample: 'Neither the teacher nor the students were present in the auditorium.',
    explanation: 'The subject adjacent to the verb position is "students" (plural), so the verb must be plural ("were").',
    frequentExamTrap: 'In interrogative sentences, the closest subject comes AFTER the auxiliary verb: "Were neither the teacher nor the students present?"',
  },
  {
    id: 'rule-sva-4',
    ruleNumber: 4,
    title: '"Each of", "Either of", "Neither of" Concord',
    topic: 'Subject–Verb Agreement',
    category: 'Grammar Foundation',
    statement: '"Each of", "Either of", "Neither of", and "One of" are followed by a PLURAL noun or pronoun, but require a strictly SINGULAR verb.',
    incorrectExample: 'Each of the participants have been given an identity card.',
    correctExample: 'Each of the participants has been given an identity card.',
    explanation: '"Each" is the distributive singular subject. "Participants" is merely the object of the preposition "of".',
    frequentExamTrap: 'Watch out for relative clauses modifying the plural noun: "He is one of those students who HAVE passed", but "He is the ONLY ONE of those students who HAS passed".',
  },
  {
    id: 'rule-sva-5',
    ruleNumber: 5,
    title: '"More than one" vs "More than two" Constructions',
    topic: 'Subject–Verb Agreement',
    category: 'Grammar Foundation',
    statement: '"More than one" takes a Singular Noun and Singular Verb. However, "More [Plural Noun] than one" takes a Plural Verb.',
    incorrectExample: 'More than one candidate were rejected during the physical test.',
    correctExample: 'More than one candidate was rejected during the physical test.',
    explanation: '"More than one" grammatically behaves as a singular modifier followed by a singular countable noun ("candidate was").',
    frequentExamTrap: 'Compare: "More than one student WAS absent" vs "More students than one WERE absent".',
  },
  {
    id: 'rule-inv-1',
    ruleNumber: 6,
    title: 'Negative Adverb Inversion ("Hardly", "Scarcely", "No sooner")',
    topic: 'Inversion & Conjunctions',
    category: 'Exam Grammar',
    statement: 'When a sentence begins with a negative adverbial ("Hardly", "Scarcely", "Barely", "No sooner", "Seldom"), partial subject-auxiliary inversion is mandatory.',
    incorrectExample: 'Hardly he had arrived at the station when the train departed.',
    correctExample: 'Hardly had he arrived at the station when the train departed.',
    explanation: 'Inversion places the auxiliary before the subject: [Hardly + had + Subject + V3]. Furthermore, "Hardly" takes "when", whereas "No sooner" takes "than".',
    frequentExamTrap: 'TCS frequently uses "then" or "that" instead of "than" with "No sooner", or uses "then" instead of "when" with "Hardly".',
  },
  {
    id: 'rule-cond-1',
    ruleNumber: 7,
    title: 'Third Conditional (Unreal Past)',
    topic: 'Conditionals',
    category: 'Grammar Foundation',
    statement: 'Past unreal conditional sentences must follow: [If + Past Perfect (had + V3)], [Subject + would have + V3].',
    incorrectExample: 'If she would have studied diligently, she would have secured AIR 1.',
    correctExample: 'If she had studied diligently, she would have secured AIR 1.',
    explanation: 'The conditional "if" clause can NEVER contain "would have". The "if" clause must remain in the Past Perfect.',
    frequentExamTrap: 'Inversion form in past conditional: "Had she studied diligently, she would have secured AIR 1."',
  },
  {
    id: 'rule-pron-1',
    ruleNumber: 8,
    title: 'Order of Personal Pronouns (231 vs 123 Rule)',
    topic: 'Pronouns',
    category: 'Grammar Foundation',
    statement: 'In pleasant, neutral, or general contexts, multiple singular personal pronouns follow the 2-3-1 order (Second, Third, First person). In confessing guilt, errors, or plural pronouns, use 1-2-3.',
    incorrectExample: 'I, you and he will complete the SSC mock syllabus together.',
    correctExample: 'You, he and I will complete the SSC mock syllabus together.',
    explanation: 'Normal cooperative positive statement requires 2nd Person (You) -> 3rd Person (He) -> 1st Person (I).',
    frequentExamTrap: 'If confessing a crime or blunder: "I, you and he are responsible for this grave mistake."',
  },
  {
    id: 'rule-prep-1',
    ruleNumber: 9,
    title: 'Fixed Preposition Prohibitions ("Comprise", "Discuss", "Order")',
    topic: 'Prepositions',
    category: 'Exam Grammar',
    statement: 'Certain transitive verbs take direct objects and MUST NOT be followed by prepositions in the active voice: comprise (no "of"), discuss (no "about"), order (no "for"), enter (no "into" for physical spaces).',
    incorrectExample: 'The committee comprises of seven senior civil servants.',
    correctExample: 'The committee comprises seven senior civil servants.',
    explanation: '"Comprise" already means "consist of". Therefore, "comprises of" is a redundant pleonasm. Note: Passive "is comprised of" is acceptable.',
    frequentExamTrap: '"Enter into" is correct ONLY for agreements, discussions, or treaties, but incorrect for entering physical rooms or halls.',
  },
  {
    id: 'rule-noun-1',
    ruleNumber: 10,
    title: 'Uncountable Nouns without Pluralization ("Scenery", "Furniture", "Information")',
    topic: 'Nouns',
    category: 'Grammar Foundation',
    statement: 'Nouns such as scenery, furniture, information, advice, luggage, baggage, poetry, machinery, and equipment are uncountable. They never take an indefinite article ("a/an") or plural "s/es".',
    incorrectExample: 'The sceneries of Kashmir were praised by all tourists.',
    correctExample: 'The scenery of Kashmir was praised by all tourists.',
    explanation: '"Scenery" cannot be made plural. To indicate singular/plural units, use counters: "a piece of advice", "articles of furniture".',
    frequentExamTrap: 'TCS often tests "informations" and "furnitures" in Tier-I sentence improvement questions.',
  },
];
