import { StudyChapter } from '../types';

export const MATHS_CHAPTERS: StudyChapter[] = [
  {
    slug: 'number-system',
    title: 'Number System: Divisibility, Remainders & Unit Digits',
    subject: 'Mathematics',
    unit: 'Unit 1: Number Systems',
    category: 'Number Systems',
    subcategory: 'Core Arithmetic & Number Theory',
    priority: 'High Priority',
    tier: 'Tier-I & II',
    estimatedMinutes: 50,
    rulesCount: 14,
    mcqsCount: 35,
    wordCount: 1850,
    summary: 'Divisibility rules from 2 to 99, unit digit cyclicity of 4, number of trailing zeroes, remainder theorems (Euler, Fermat, Wilson), and factor counts.',
    order: 1,
    nextSlug: 'percentage',
    favouriteTrap: 'Confusing cyclicity of unit digit powers (e.g. 7⁴ = 2401 ending in 1, so 7^(4k) has unit digit 1, but 7^(4k) mod 4 = 0, so candidate mistakes 0 power for 1).',
    memoryTrick: 'If remainder is 0 when dividing exponent by 4, use power 4 (not 0): 7^4 = ends in 1.',
    sections: [
      {
        title: '1. Introduction & Exam Weightage',
        type: 'intro',
        content: 'Number System is the bedrock of Quantitative Aptitude, delivering 2 to 4 questions in Tier-I and Tier-II. SSC frequently tests divisibility of combined composite numbers (e.g., divisible by 72, 88, or 99), remainder theorems, unit digit extraction of large exponentials, and prime factorizations.',
      },
      {
        title: '2. Master Divisibility Rules Table (2 to 99)',
        type: 'concept',
        content: 'Quick-check divisibility rules for high-speed calculation:',
        table: {
          title: 'Divisibility Rules for Common and Composite Divisors',
          headers: ['Divisor', 'Operational Divisibility Condition', 'Exam Application Example'],
          rows: [
            ['2, 4, 8, 16', 'Last 1, 2, 3, or 4 digits must be divisible by 2, 4, 8, or 16 respectively', 'For 8: Test only last 3 digits; for 16: Test last 4 digits'],
            ['3 and 9', 'Sum of all digits must be divisible by 3 or 9 respectively', 'Digital sum method allows instant elimination'],
            ['5 and 25', 'Last digit is 0/5 (for 5); last 2 digits are 00, 25, 50, 75 (for 25)', 'Direct inspection of terminal digits'],
            ['7, 11, 13', 'Osculating triplet rule: Difference between sum of digits in alternate 3-digit blocks (from right)', 'e.g. 614,355 → 355 - 614 = -259; 259 ÷ 7 = 37 (divisible by 7)'],
            ['11', 'Difference between (Sum of digits at odd places) and (Sum of digits at even places) is 0 or multiple of 11', 'Crucial in missing digit questions like 738A6A divisible by 11'],
            ['72 (8 × 9)', 'Number must be co-prime divisible by BOTH 8 and 9', 'Step 1: Use last 3 digits for 8 to find y; Step 2: Use digital sum for 9 to find x'],
            ['88 (8 × 11)', 'Number must be co-prime divisible by BOTH 8 and 11', 'Find y via last 3 digits with 8; find x via alternating sum with 11'],
            ['99 (9 × 11)', 'Number must be co-prime divisible by BOTH 9 and 11', 'Sum of digits divisible by 9 AND odd-even difference divisible by 11'],
          ],
        },
      },
      {
        title: '3. Unit Digit Cyclicity Theorem',
        type: 'rules',
        content: 'Cyclicity of powers for single digits under base-10 arithmetic:',
        rulesList: [
          {
            ruleNo: 1,
            title: 'Cyclicity of 1 (Invariable Digits)',
            statement: 'Digits 0, 1, 5, 6 raised to ANY positive integer power n always retain their identity: (..0)^n = 0, (..1)^n = 1, (..5)^n = 5, (..6)^n = 6.',
            incorrect: 'Calculating powers of 5 or 6.',
            correct: 'Directly write 5 or 6 without division.',
            trapNote: 'Even if the power is huge (e.g. 526^987), the unit digit remains 6.',
          },
          {
            ruleNo: 2,
            title: 'Cyclicity of 2 (Digits 4 and 9)',
            statement: 'Digits 4 and 9 have a period of 2:\n• 4^(Odd) ends in 4; 4^(Even) ends in 6.\n• 9^(Odd) ends in 9; 9^(Even) ends in 1.',
            incorrect: 'Dividing power by 4 when checking 4 and 9.',
            correct: 'Simply check whether the exponent is odd or even.',
            trapNote: '4^1 = 4, 4^2 = 16, 4^3 = 64; 9^1 = 9, 9^2 = 81, 9^3 = 729.',
          },
          {
            ruleNo: 3,
            title: 'Cyclicity of 4 (Digits 2, 3, 7, 8)',
            statement: 'Digits 2, 3, 7, 8 repeat in cycles of 4. Divide exponent by 4: remainder r gives the effective power. If remainder r = 0, use effective power 4.',
            incorrect: 'Using power 0 when remainder is 0 (which would give 1).',
            correct: 'If remainder is 0, effective power is 4: 2^4 ends in 6; 3^4 ends in 1; 7^4 ends in 1; 8^4 ends in 6.',
            trapNote: '7^44: 44 ÷ 4 gives remainder 0, so unit digit is 7^4 = ends in 1, NOT 7^0 = 1.',
          },
        ],
      },
      {
        title: '4. Number of Trailing Zeroes & Factors',
        type: 'formulas',
        content: 'Standard formulas for trailing zeroes and factors of N = p^a · q^b · r^c (where p, q, r are prime factors):',
        mathFormulas: [
          '\\text{Trailing Zeroes in } n! = \\left\\lfloor\\frac{n}{5}\\right\\rfloor + \\left\\lfloor\\frac{n}{25}\\right\\rfloor + \\left\\lfloor\\frac{n}{125}\\right\\rfloor + \\dots',
          '\\text{Total Number of Factors of } N = (a + 1)(b + 1)(c + 1)',
          '\\text{Sum of Factors} = \\frac{p^{a+1} - 1}{p - 1} \\times \\frac{q^{b+1} - 1}{q - 1} \\times \\frac{r^{c+1} - 1}{r - 1}',
          '\\text{Number of Even Factors (if } p=2) = a(b + 1)(c + 1)',
          '\\text{Number of Odd Factors} = (b + 1)(c + 1) \\quad (\\text{exclude } 2^a)',
        ],
      },
      {
        title: '5. Solved Examples (Step-by-Step)',
        type: 'examples',
        content: 'Worked problems from official SSC CGL exams.',
        solvedExamples: [
          {
            level: 'Moderate',
            question: 'Find the number of trailing zeroes in 100!.\n(A) 20  (B) 24  (C) 25  (D) 22',
            solution: 'The number of trailing zeroes in n! equals the exponent of the prime factor 5 in n! (Legendre’s Formula):\nNumber of zeroes = ⌊100 / 5⌋ + ⌊100 / 25⌋ + ⌊100 / 125⌋\n= 20 + 4 + 0 = 24 trailing zeroes.\nCorrect Answer: (B)',
            fastTrick: '100/5 = 20; 20/5 = 4; 20 + 4 = 24.',
          },
          {
            level: 'SSC-level',
            question: 'If the 9-digit number 985x3678y is completely divisible by 72, then what is the value of (4x - 3y)?\n(A) 3  (B) 4  (C) -2  (D) 6',
            solution: 'Since 72 = 8 × 9 (where 8 and 9 are co-prime):\nStep 1: Test divisibility by 8 (last 3 digits "78y" must be divisible by 8):\n780 ÷ 8 = 97 with remainder 4.\nTo be divisible by 8, 78y must be 784 (since 784 ÷ 8 = 98). Hence, y = 4.\n\nStep 2: Test divisibility by 9 (sum of digits must be divisible by 9):\nSum of digits = 9 + 8 + 5 + x + 3 + 6 + 7 + 8 + y\n= 46 + x + y = 46 + x + 4 = 50 + x.\nThe nearest multiple of 9 greater than or equal to 50 is 54.\n50 + x = 54 ⟹ x = 4.\n\nStep 3: Calculate (4x - 3y):\n4x - 3y = 4(4) - 3(4) = 16 - 12 = 4.\nCorrect Answer: (B)',
            fastTrick: 'y = 4 (784/8=98), x = 4 (sum=54), 4(4) - 3(4) = 4.',
            trapNote: 'Always verify whether the question asks for (4x - 3y) or √(4x - 3y).',
          },
        ],
      },
      {
        title: '6. Practice Questions',
        type: 'practice',
        content: 'Solve to test your speed.',
        practiceQuestions: [
          {
            id: 'num-p-1',
            question: 'What is the unit digit in the product (7^95 - 3^58)?',
            options: ['0', '4', '6', '7'],
            correctIndex: 1,
            explanation: 'Unit digit of 7^95: 95 ÷ 4 gives remainder 3 ⟹ 7³ = 343 (Unit digit 3).\nUnit digit of 3^58: 58 ÷ 4 gives remainder 2 ⟹ 3² = 9 (Unit digit 9).\nDifference = 3 - 9. Since 7^95 > 3^58, borrow 10: 13 - 9 = 4.',
            sourceType: 'PYQ-style',
          },
        ],
      },
      {
        title: '7. Quick Revision Summary',
        type: 'revision',
        content: '• Divisibility by 72 = Check 8 (last 3 digits) and 9 (digital sum).\n• Divisibility by 88 = Check 8 (last 3 digits) and 11 (odd-even difference).\n• Trailing zeroes in n! = sum of ⌊n/5^k⌋.\n• Total factors of p^a · q^b = (a + 1)(b + 1).\n• When borrowing in unit digit subtraction: (3 - 9) becomes (13 - 9) = 4.',
      },
    ],
  },
  {
    slug: 'percentage',
    title: 'Percentage & Base-Shift Delta Shortcuts',
    subject: 'Mathematics',
    unit: 'Unit 2: Commercial Mathematics',
    category: 'Arithmetic',
    subcategory: 'Fundamental Arithmetic',
    priority: 'High Priority',
    tier: 'Tier-I & II',
    estimatedMinutes: 40,
    rulesCount: 10,
    mcqsCount: 30,
    wordCount: 1600,
    summary: 'Fractional equivalents, reciprocal base-shift delta, successive percentage formula, and consumption expenditure traps.',
    order: 2,
    prevSlug: 'number-system',
    nextSlug: 'profit-loss-discount',
    favouriteTrap: 'Calculating percentage decrease on the original base rather than on the augmented base.',
    memoryTrick: '+1/x increase is counterbalanced by -1/(x+1) decrease to maintain constant product.',
    sections: [
      {
        title: '1. Core Concept & Fractional Chart',
        type: 'concept',
        content: 'Percentage is arithmetic calculation evaluated per 100 parts. Rapid non-pen calculation requires immediate familiarity with fraction-to-percentage conversions: 1/2 = 50%, 1/3 = 33.33%, 1/4 = 25%, 1/5 = 20%, 1/6 = 16.67%, 1/7 = 14.28%, 1/8 = 12.5%, 1/9 = 11.11%, 1/11 = 9.09%, 1/12 = 8.33%, 1/16 = 6.25%.',
      },
      {
        title: '2. Base-Shift Reciprocal Delta Theorem',
        type: 'formulas',
        content: 'When two quantities multiply to form a constant product (Price × Consumption = Expenditure, Speed × Time = Distance), any fractional change in one dictates a reciprocal change in the other.',
        mathFormulas: [
          '+\\frac{1}{x} \\;\\text{increase} \\implies -\\frac{1}{x + 1} \\;\\text{decrease}',
          '-\\frac{1}{x} \\;\\text{decrease} \\implies +\\frac{1}{x - 1} \\;\\text{increase}',
        ],
      },
      {
        title: '3. SSC Example & Fast Solution Method',
        type: 'examples',
        content: 'Problem: If the price of petrol increases by 25%, by what percentage must a motorist reduce his consumption so that expenditure remains unchanged?\n\nFast Method:\n25% = +1/4 increase.\nCorresponding reduction in consumption = -1/(4 + 1) = -1/5 = 20%.\nSolved in 3 seconds without algebra or assumed 100-base equations.',
      },
      {
        title: '4. Successive Percentage Formula',
        type: 'formulas',
        content: 'When a quantity undergoes two consecutive percentage changes of a% and b%:',
        mathFormulas: [
          '\\text{Net Percentage Change} = a + b + \\frac{a \\times b}{100}',
        ],
      },
      {
        title: '5. Common Mistakes & Traps',
        type: 'traps',
        content: '1. In successive discounts of 20% and 10%, do NOT add them to get 30%. The net discount is: -20 - 10 + (20 × 10)/100 = -28%.\n2. When population increases by 10% in Year 1 and decreases by 10% in Year 2, the net change is NOT 0%. It is 10 - 10 - (100/100) = -1% (net decrease of 1%).',
      },
      {
        title: '6. Quick Revision Summary',
        type: 'revision',
        content: '• Expenditure = Price × Consumption.\n• If Price increases by a/b, Consumption reduces by a/(a + b).\n• If Price decreases by a/b, Consumption increases by a/(b - a).\n• Net Area change of rectangle with length +l% and breadth +b% = l + b + (lb/100).',
      },
    ],
  },
  {
    slug: 'profit-loss-discount',
    title: 'Profit, Loss & Discount (CP, SP, MP & Dishonest Shopkeeper)',
    subject: 'Mathematics',
    unit: 'Unit 2: Commercial Mathematics',
    category: 'Commercial Math',
    subcategory: 'Retail Arithmetic',
    priority: 'High Priority',
    tier: 'Tier-I & II',
    estimatedMinutes: 45,
    rulesCount: 12,
    mcqsCount: 30,
    wordCount: 1700,
    summary: 'CP/SP/MP golden triangle, markup percentage, successive discounts, free article equivalents, and dishonest dealer false weight formulas.',
    order: 3,
    prevSlug: 'percentage',
    nextSlug: 'simple-compound-interest',
    favouriteTrap: 'Calculating markup on Selling Price instead of Cost Price, or confusing discount base (Discount is ALWAYS on Marked Price MP, Profit is on CP).',
    memoryTrick: 'CP : MP Ratio Theorem: CP / MP = (100 - Discount%) / (100 + Profit%). This single ratio formula solves 80% of SSC profit-discount problems directly!',
    sections: [
      {
        title: '1. Introduction & Golden Triangle',
        type: 'intro',
        content: 'Profit, Loss & Discount constitutes 2 to 3 questions in Tier-I and Tier-II. The fundamental chain of commerce connects three prices: Cost Price (CP) → Marked Price (MP) → Selling Price (SP). Profit/Loss connects CP and SP; Discount connects MP and SP; Markup connects CP and MP.',
      },
      {
        title: '2. The Master CP : MP Golden Ratio Formula',
        type: 'formulas',
        content: 'When an article is sold at a discount of D% and still yields a profit of P%:',
        mathFormulas: [
          '\\frac{\\text{Cost Price (CP)}}{\\text{Marked Price (MP)}} = \\frac{100 - \\text{Discount}\\%}{100 + \\text{Profit}\\%}',
          '\\text{Selling Price (SP)} = \\text{CP} \\times \\left(1 + \\frac{P}{100}\\right) = \\text{MP} \\times \\left(1 - \\frac{D}{100}\\right)',
          '\\text{Markup}\\% = \\frac{\\text{MP} - \\text{CP}}{\\text{CP}} \\times 100\\%',
        ],
      },
      {
        title: '3. Dishonest Dealer & False Weight Formula',
        type: 'formulas',
        content: 'When a dishonest merchant claims to sell goods at cost price but uses a false weight of w grams instead of true weight W grams:',
        mathFormulas: [
          '\\text{Profit}\\% = \\frac{\\text{True Weight} - \\text{False Weight}}{\\text{False Weight}} \\times 100\\% = \\frac{\\text{Error}}{\\text{True Value} - \\text{Error}} \\times 100\\%',
        ],
      },
      {
        title: '4. Free Article Promotion Discount Equivalents',
        type: 'rules',
        content: 'Retail promotion conversions to percentage discount:',
        rulesList: [
          {
            ruleNo: 1,
            title: 'Buy x, Get y Free',
            statement: 'When a retailer offers "Buy x, Get y Free", the total items given away = (x + y). The discount is calculated as:\nDiscount % = [y / (x + y)] × 100%.',
            incorrect: 'Calculating discount as (y / x) × 100%.',
            correct: 'Discount % = [Free Articles / Total Articles Transferred] × 100%.',
            trapNote: '"Buy 4, Get 1 Free" = 1 / (4 + 1) = 1/5 = 20% discount (NOT 25%).',
          },
        ],
      },
      {
        title: '5. Solved Examples (Step-by-Step)',
        type: 'examples',
        content: 'Standard SSC CGL exam problems.',
        solvedExamples: [
          {
            level: 'Moderate',
            question: 'A trader marks his goods so as to make a profit of 20% after giving a discount of 10%. If the cost price is ₹450, what is the marked price?\n(A) ₹540  (B) ₹600  (C) ₹580  (D) ₹620',
            solution: 'Apply the Golden Ratio Formula directly:\nCP / MP = (100 - Discount%) / (100 + Profit%)\n450 / MP = (100 - 10) / (100 + 20) = 90 / 120 = 3 / 4\nMP = 450 × (4 / 3) = ₹600.\nCorrect Answer: (B)',
            fastTrick: 'CP:MP = 90:120 = 3:4. Since 3 units = ₹450, 4 units = ₹600.',
          },
          {
            level: 'SSC-level',
            question: 'A dishonest shopkeeper promises to sell his goods at cost price, but uses an 800 g weight instead of a 1 kg weight. Find his actual profit percentage.\n(A) 20%  (B) 25%  (C) 16.67%  (D) 22.5%',
            solution: 'Use the False Weight Profit formula:\nProfit % = [(True Weight - False Weight) / False Weight] × 100%\nProfit % = [(1000 - 800) / 800] × 100%\n= (200 / 800) × 100% = 1/4 × 100% = 25%.\nCorrect Answer: (B)',
            fastTrick: 'Gains 200 g on an investment of 800 g: 200/800 = 1/4 = 25%.',
            trapNote: 'Candidates frequently divide by 1000 g and choose 20% (Option A).',
          },
        ],
      },
      {
        title: '6. Quick Revision Summary',
        type: 'revision',
        content: '• CP / MP = (100 - D%) / (100 + P%).\n• Buy x Get y Free: Discount % = [y / (x + y)] × 100%.\n• Dishonest dealer profit % = (Error / False Weight) × 100%.\n• Two successive discounts a% and b%: Net discount = a + b - (ab / 100).',
      },
    ],
  },
  {
    slug: 'simple-compound-interest',
    title: 'Simple & Compound Interest (CI - SI Differences & Installments)',
    subject: 'Mathematics',
    unit: 'Unit 2: Commercial Mathematics',
    category: 'Commercial Math',
    subcategory: 'Interest & Finance',
    priority: 'High Priority',
    tier: 'Tier-I & II',
    estimatedMinutes: 45,
    rulesCount: 10,
    mcqsCount: 30,
    wordCount: 1650,
    summary: 'Direct CI-SI difference formulas for 2 and 3 years, semi-annual compounding, effective annual rate, and loan installment calculations.',
    order: 4,
    prevSlug: 'profit-loss-discount',
    nextSlug: 'time-and-work',
    favouriteTrap: 'Forgetting to halve the interest rate (R/2) and double the time (2T) during semi-annual / half-yearly compounding.',
    memoryTrick: '2-Year CI - SI difference = P(R/100)². 3-Year CI - SI difference = P(R/100)² × (3 + R/100). Memorize this product!',
    sections: [
      {
        title: '1. Introduction & Interest Mechanics',
        type: 'intro',
        content: 'Simple and Compound Interest accounts for 1 to 2 questions in Tier-I and Tier-II. Simple Interest (SI) grows linearly on the original principal P, while Compound Interest (CI) grows exponentially as earned interest earns further interest in each successive period.',
      },
      {
        title: '2. The 2-Year & 3-Year CI - SI Difference Formulas',
        type: 'formulas',
        content: 'High-speed formulas tested constantly by SSC:',
        mathFormulas: [
          '\\text{Difference for 2 Years } (D_2) = P \\left(\\frac{R}{100}\\right)^2',
          '\\text{Difference for 3 Years } (D_3) = P \\left(\\frac{R}{100}\\right)^2 \\times \\left(3 + \\frac{R}{100}\\right) = D_2 \\times \\left(3 + \\frac{R}{100}\\right)',
          '\\frac{D_3}{D_2} = 3 + \\frac{R}{100}',
        ],
      },
      {
        title: '3. Compounding Frequency Rules',
        type: 'rules',
        content: 'When interest is compounded other than annually:',
        rulesList: [
          {
            ruleNo: 1,
            title: 'Half-Yearly (Semi-Annual) Compounding',
            statement: 'Rate becomes R\' = R / 2; Number of compounding cycles becomes n = 2 × T.',
            incorrect: 'Keeping original rate R with 2T periods.',
            correct: 'Both rate must be halved and time doubled.',
            trapNote: '10% per annum compounded half-yearly for 1 year = 5% per cycle for 2 cycles ⟹ Effective rate = 10.25%.',
          },
          {
            ruleNo: 2,
            title: 'Quarterly Compounding',
            statement: 'Rate becomes R\' = R / 4; Number of cycles becomes n = 4 × T.',
            incorrect: 'Using 3 periods for quarterly (confusing 3 months with 3 cycles).',
            correct: 'One year has 4 quarters; rate is divided by 4.',
            trapNote: '20% p.a. compounded quarterly for 9 months = 5% for 3 cycles.',
          },
        ],
      },
      {
        title: '4. Solved Examples (Step-by-Step)',
        type: 'examples',
        content: 'SSC exam-tested difference calculations.',
        solvedExamples: [
          {
            level: 'Moderate',
            question: 'The difference between simple and compound interest on a certain sum of money for 2 years at 10% per annum is ₹65. Find the sum.\n(A) ₹6,500  (B) ₹6,000  (C) ₹7,000  (D) ₹6,250',
            solution: 'Apply the 2-Year Difference formula:\nD₂ = P(R / 100)²\n65 = P(10 / 100)² = P(1 / 10)² = P / 100\nP = 65 × 100 = ₹6,500.\nCorrect Answer: (A)',
            fastTrick: 'P = D / (R/100)² = 65 / (0.10)² = 65 / 0.01 = ₹6,500.',
          },
        ],
      },
      {
        title: '5. Practice Questions',
        type: 'practice',
        content: 'Test yourself on 3-year differences.',
        practiceQuestions: [
          {
            id: 'ci-p-1',
            question: 'The ratio of difference between CI and SI for 3 years to that of 2 years on a certain sum at the same rate of interest is 31 : 10. What is the rate of interest per annum?',
            options: ['10%', '12%', '15%', '8%'],
            correctIndex: 0,
            explanation: 'D3 / D2 = 3 + (R / 100). Given 31 / 10 = 3.1. So 3 + (R / 100) = 3.1 ⟹ R / 100 = 0.1 ⟹ R = 10%.',
            sourceType: 'PYQ-style',
          },
        ],
      },
      {
        title: '6. Quick Revision Summary',
        type: 'revision',
        content: '• 2-Year CI - SI difference = P(R/100)².\n• D3 / D2 = 3 + (R/100).\n• Half-yearly compounding: R → R/2, T → 2T.\n• Quarterly compounding: R → R/4, T → 4T.',
      },
    ],
  },
  {
    slug: 'time-and-work',
    title: 'Time & Work: LCM Efficiency Method & Men-Days-Hours',
    subject: 'Mathematics',
    unit: 'Unit 2: Commercial Mathematics',
    category: 'Commercial Math',
    subcategory: 'Work & Energy',
    priority: 'High Priority',
    tier: 'Tier-I & II',
    estimatedMinutes: 40,
    rulesCount: 8,
    mcqsCount: 30,
    wordCount: 1600,
    summary: 'LCM total work assumption, individual unit efficiency, alternate day work, wage division by work done, and the Man-Day-Hour work equivalence theorem.',
    order: 5,
    prevSlug: 'simple-compound-interest',
    nextSlug: 'time-speed-distance',
    favouriteTrap: 'Dividing wages in the ratio of days worked instead of work done (Efficiency × Days).',
    memoryTrick: 'Total Work = LCM of Days. Daily Efficiency = Total Work / Days. Everything reduces to simple integer addition!',
    sections: [
      {
        title: '1. The LCM Total Work Technique',
        type: 'concept',
        content: 'Never use traditional fractional addition (1/12 + 1/15) in competitive exams. Instead:\nStep 1: Assume Total Work = LCM of individual completion days.\nStep 2: Calculate daily efficiency (units/day) = Total Work ÷ Individual Days.\nStep 3: Combine or subtract efficiencies based on question conditions.',
      },
      {
        title: '2. The MDH / W Work Equivalence Formula',
        type: 'formulas',
        content: 'For group work involving Men (M), Days (D), Hours per day (H), and Work done (W):',
        mathFormulas: [
          '\\frac{M_1 \\times D_1 \\times H_1 \\times E_1}{W_1} = \\frac{M_2 \\times D_2 \\times H_2 \\times E_2}{W_2}',
        ],
      },
      {
        title: '3. Solved Examples (Step-by-Step)',
        type: 'examples',
        content: 'Worked problems illustrating efficiency methods.',
        solvedExamples: [
          {
            level: 'Moderate',
            question: 'A can complete a piece of work in 12 days and B in 15 days. They worked together for 4 days, after which A left. In how many more days will B finish the remaining work?\n(A) 5 days  (B) 6 days  (C) 4 days  (D) 7 days',
            solution: 'Step 1: Total Work = LCM(12, 15) = 60 units.\nStep 2: Efficiency of A = 60 / 12 = 5 units/day.\nEfficiency of B = 60 / 15 = 4 units/day.\nCombined efficiency of (A + B) = 5 + 4 = 9 units/day.\n\nStep 3: Work completed in first 4 days = 4 × 9 = 36 units.\nRemaining work = 60 - 36 = 24 units.\n\nStep 4: Days required by B alone to finish remaining work:\nTime = Remaining Work / Efficiency of B = 24 / 4 = 6 days.\nCorrect Answer: (B)',
            fastTrick: 'Total 60. First 4 days: 36 units done. 24 units left. 24/4 = 6 days.',
          },
        ],
      },
      {
        title: '4. Practice Questions',
        type: 'practice',
        content: 'Solve alternate day problems.',
        practiceQuestions: [
          {
            id: 'w和服务-p-1',
            question: '12 men can complete a work in 16 days. In how many days can 16 men complete the same work?',
            options: ['12 days', '10 days', '14 days', '16 days'],
            correctIndex: 0,
            explanation: 'M1 × D1 = M2 × D2 ⟹ 12 × 16 = 16 × D2 ⟹ D2 = 12 days.',
            sourceType: 'PYQ-style',
          },
        ],
      },
      {
        title: '5. Quick Revision Summary',
        type: 'revision',
        content: '• Total Work = LCM of given days.\n• Daily Efficiency = Work / Days.\n• M1·D1·H1 / W1 = M2·D2·H2 / W2.\n• Wages are shared strictly in proportion to work done (Efficiency × Days).',
      },
    ],
  },
  {
    slug: 'time-speed-distance',
    title: 'Time, Speed & Distance: Trains, Boats & Relative Velocity',
    subject: 'Mathematics',
    unit: 'Unit 2: Commercial Mathematics',
    category: 'Commercial Math',
    subcategory: 'Kinematics & Motion',
    priority: 'High Priority',
    tier: 'Tier-I & II',
    estimatedMinutes: 45,
    rulesCount: 11,
    mcqsCount: 30,
    wordCount: 1700,
    summary: 'Unit conversion factor 5/18, harmonic average speed, relative motion in same/opposite directions, train platform crossing, and upstream/downstream boats.',
    order: 6,
    prevSlug: 'time-and-work',
    nextSlug: 'triangles-geometry',
    favouriteTrap: 'Averaging speeds directly as (x + y)/2 instead of harmonic mean 2xy/(x + y) when distances are equal.',
    memoryTrick: 'km/h to m/s: Multiply by 5/18 (going to smaller unit, so smaller number 5 on top). m/s to km/h: Multiply by 18/5.',
    sections: [
      {
        title: '1. Core Conversions & Harmonic Average Speed',
        type: 'formulas',
        content: 'Fundamental motion relationships:',
        mathFormulas: [
          '\\text{Speed (m/s)} = \\text{Speed (km/h)} \\times \\frac{5}{18}, \\quad \\text{Speed (km/h)} = \\text{Speed (m/s)} \\times \\frac{18}{5}',
          '\\text{Average Speed (Equal Distances)} = \\frac{2xy}{x + y}',
          '\\text{Average Speed (General)} = \\frac{\\text{Total Distance Covered}}{\\text{Total Time Taken}}',
        ],
      },
      {
        title: '2. Relative Speed & Train Mechanics',
        type: 'rules',
        content: 'Rules for trains and moving bodies:',
        rulesList: [
          {
            ruleNo: 1,
            title: 'Relative Speed: Same vs Opposite Direction',
            statement: '• Opposite Direction (Moving towards each other): Relative Speed = S1 + S2.\n• Same Direction (Chasing): Relative Speed = |S1 - S2|.',
            incorrect: 'Adding speeds when moving in the same direction.',
            correct: 'Subtract speeds when moving in the same direction.',
            trapNote: 'Convert both speeds to m/s before adding/subtracting if distances are in meters.',
          },
          {
            ruleNo: 2,
            title: 'Train Crossing Platform / Bridge vs Pole',
            statement: '• Crossing Pole / Standing Man: Distance = Length of Train (L).\n• Crossing Platform / Bridge / Tunnel: Distance = Length of Train (L) + Length of Platform (P).',
            incorrect: 'Ignoring platform length in distance calculation.',
            correct: 'Total distance = L_train + L_platform.',
            trapNote: 'Time = (L_train + L_platform) / Speed_train.',
          },
        ],
      },
      {
        title: '3. Boats & Streams Formulas',
        type: 'formulas',
        content: 'Let speed of boat in still water = u km/h, and speed of river stream = v km/h:',
        mathFormulas: [
          '\\text{Downstream Speed } (D) = u + v',
          '\\text{Upstream Speed } (U) = u - v',
          '\\text{Speed of Boat in Still Water } (u) = \\frac{D + U}{2}',
          '\\text{Speed of Stream } (v) = \\frac{D - U}{2}',
        ],
      },
      {
        title: '4. Solved Examples (Step-by-Step)',
        type: 'examples',
        content: 'SSC CGL train and boat problems.',
        solvedExamples: [
          {
            level: 'Moderate',
            question: 'A train 180 m long is running at a speed of 72 km/h. In how much time will it pass a platform 120 m long?\n(A) 12 seconds  (B) 15 seconds  (C) 18 seconds  (D) 20 seconds',
            solution: 'Step 1: Convert speed to m/s:\nSpeed = 72 × (5 / 18) = 4 × 5 = 20 m/s.\n\nStep 2: Calculate total distance to be covered:\nTotal Distance = Length of Train + Length of Platform = 180 + 120 = 300 m.\n\nStep 3: Calculate time taken:\nTime = Distance / Speed = 300 / 20 = 15 seconds.\nCorrect Answer: (B)',
            fastTrick: 'Speed = 20 m/s. Total distance = 300 m. Time = 300/20 = 15 s.',
          },
        ],
      },
      {
        title: '5. Quick Revision Summary',
        type: 'revision',
        content: '• km/h to m/s: multiply by 5/18.\n• Average speed for equal distance = 2xy / (x + y).\n• Relative speed: Same direction = S1 - S2; Opposite direction = S1 + S2.\n• Boat in still water u = (D + U)/2; Stream v = (D - U)/2.',
      },
    ],
  },
  {
    slug: 'triangles-geometry',
    title: 'Triangles, Centers & Incircle Theorems',
    subject: 'Mathematics',
    unit: 'Unit 3: Advanced Mathematics',
    category: 'Advanced Quant',
    subcategory: 'Pure Geometry',
    priority: 'High Priority',
    tier: 'Tier-I & II',
    estimatedMinutes: 50,
    rulesCount: 15,
    mcqsCount: 35,
    wordCount: 1800,
    summary: 'Inradius in right triangles, circumradius, centroid 2:1 division, orthocenter angle, and similarity area ratios.',
    order: 7,
    prevSlug: 'time-speed-distance',
    nextSlug: 'mensuration-2d',
    favouriteTrap: 'Confusing the angle formed by angle bisectors (Incentre) with the angle formed by altitudes (Orthocentre).',
    memoryTrick: 'Incentre: 90° + A/2. Orthocentre: 180° - A. Circumcentre: 2A.',
    sections: [
      {
        title: '1. Triangle Centers Taxonomy',
        type: 'concept',
        content: 'A triangle possesses 4 cardinal centers:\n1. Centroid (G): Intersection of medians. Divides median in 2:1 ratio from vertex.\n2. Incentre (I): Intersection of internal angle bisectors. Equidistant from all three sides.\n3. Circumcentre (O): Intersection of perpendicular side bisectors. Equidistant from all three vertices.\n4. Orthocentre (H): Intersection of altitudes.',
        diagram: {
          type: 'triangle',
          title: 'Cardinal Centers of a Triangle: Centroid, Incentre, Circumcentre, Orthocentre',
          caption: 'Centroid (2:1 median ratio), Incentre (equidistant from sides), Circumcentre (equidistant from vertices)',
        },
      },
      {
        title: '2. Key Angle Theorems at Triangle Centers',
        type: 'formulas',
        content: 'Angles subtended at the respective centers by side BC:',
        mathFormulas: [
          '\\angle BIC = 90^\\circ + \\frac{\\angle A}{2} \\quad (\\text{Incentre})',
          '\\angle BOC = 2\\angle A \\quad (\\text{Circumcentre})',
          '\\angle BHC = 180^\\circ - \\angle A \\quad (\\text{Orthocentre})',
        ],
      },
      {
        title: '3. Inradius Formula for Right-Angled Triangle',
        type: 'formulas',
        content: 'For a right triangle with perpendicular legs a and b, and hypotenuse c:',
        mathFormulas: [
          'r = \\frac{a + b - c}{2} = s - c, \\quad R = \\frac{c}{2}',
        ],
      },
      {
        title: '4. SSC Example: 5-12-13 Triangle',
        type: 'examples',
        content: 'Problem: Find the radius of the circle inscribed in a right-angled triangle with sides 5 cm, 12 cm, and 13 cm.\n\nSolution:\nPerpendicular sides: a = 5, b = 12. Hypotenuse: c = 13.\nr = (5 + 12 - 13) / 2 = 4 / 2 = 2 cm.\nCircumradius R = c / 2 = 13 / 2 = 6.5 cm.\nDistance between Circumcentre and Incentre = √(R² - 2Rr) = √(42.25 - 26) = √16.25 cm.',
      },
      {
        title: '5. Quick Revision Summary',
        type: 'revision',
        content: '• In an equilateral triangle of side a: Inradius r = a/(2√3), Circumradius R = a/√3. R : r = 2 : 1.\n• Ratio of areas: Area of Circumcircle : Area of Incircle = 4 : 1.\n• Area ratio of two similar triangles equals the square of the ratio of their corresponding sides, medians, or heights.',
      },
    ],
  },
  {
    slug: 'mensuration-2d',
    title: 'Mensuration 2D: Circles, Polygons & Cyclic Quads',
    subject: 'Mathematics',
    unit: 'Unit 3: Advanced Mathematics',
    category: 'Advanced Quant',
    subcategory: 'Geometry & Mensuration',
    priority: 'High Priority',
    tier: 'Tier-I & II',
    estimatedMinutes: 45,
    rulesCount: 12,
    mcqsCount: 30,
    wordCount: 1650,
    summary: 'Ptolemy’s theorem, Brahmagupta’s area formula, rhombus diagonal relations, and sector circular geometry.',
    order: 8,
    prevSlug: 'triangles-geometry',
    nextSlug: 'trigonometry',
    favouriteTrap: 'Applying Brahmagupta’s cyclic formula to general non-cyclic quadrilaterals.',
    memoryTrick: 'Ptolemy: Product of Diagonals = Sum of Products of Opposite Sides.',
    sections: [
      {
        title: '1. Cyclic Quadrilateral Theorems',
        type: 'concept',
        content: 'A cyclic quadrilateral has all 4 vertices lying on a single circle. Opposite angles always sum to 180°: ∠A + ∠C = 180° and ∠B + ∠D = 180°.\n\nTwo crucial theorems tested repeatedly in SSC CGL:',
      },
      {
        title: '2. Ptolemy’s Theorem & Brahmagupta’s Formula',
        type: 'formulas',
        content: 'For consecutive sides a, b, c, d and diagonals d1, d2:',
        mathFormulas: [
          'd_1 \\times d_2 = (a \\times c) + (b \\times d) \\quad (\\text{Ptolemy})',
          '\\text{Area} = \\sqrt{(s - a)(s - b)(s - c)(s - d)}, \\quad s = \\frac{a + b + c + d}{2}',
        ],
      },
      {
        title: '3. Rhombus & Trapezium Essential Formulas',
        type: 'formulas',
        content: 'Rhombus diagonals bisect each other perpendicularly at 90°:',
        mathFormulas: [
          '\\text{Area of Rhombus} = \\frac{1}{2} \\times d_1 \\times d_2, \\quad 4a^2 = d_1^2 + d_2^2',
          '\\text{Area of Trapezium} = \\frac{1}{2} \\times (a + b) \\times h',
        ],
      },
      {
        title: '4. Quick Revision Summary',
        type: 'revision',
        content: '• Perimeter of a semicircle = πr + 2r = r(π + 2) = 36r/7 (when π = 22/7).\n• Area of a circle sector with angle θ = (θ/360°) × πr².\n• Arc length of a sector = (θ/360°) × 2πr.',
      },
    ],
  },
  {
    slug: 'trigonometry',
    title: 'Trigonometry & Heights and Distances',
    subject: 'Mathematics',
    unit: 'Unit 3: Advanced Mathematics',
    category: 'Advanced Quant',
    subcategory: 'Trigonometry',
    priority: 'High Priority',
    tier: 'Tier-I & II',
    estimatedMinutes: 45,
    rulesCount: 14,
    mcqsCount: 30,
    wordCount: 1750,
    summary: 'Pythagorean trigonometric identities, values table, maximum & minimum of a sin θ + b cos θ, and 30-60-90 / 45-45-90 ratio triangles.',
    order: 9,
    prevSlug: 'mensuration-2d',
    favouriteTrap: 'Overlooking that sin²θ + cos²θ = 1 holds for all θ, but sec²θ - tan²θ = 1 holds only when cos θ ≠ 0.',
    memoryTrick: 'Maximum of (a sin θ + b cos θ) = +√(a² + b²); Minimum = -√(a² + b²).',
    sections: [
      {
        title: '1. Fundamental Identities & Angle Values Table',
        type: 'concept',
        content: 'The 3 foundational trigonometric identities and standard angles table:',
        table: {
          title: 'Trigonometric Values for Standard Angles (0° to 90°)',
          headers: ['Ratio', '0°', '30°', '45°', '60°', '90°'],
          rows: [
            ['sin θ', '0', '1/2', '1/√2', '√3/2', '1'],
            ['cos θ', '1', '√3/2', '1/√2', '1/2', '0'],
            ['tan θ', '0', '1/√3', '1', '√3', 'Not Defined (∞)'],
            ['cosec θ', 'Not Defined', '2', '√2', '2/√3', '1'],
            ['sec θ', '1', '2/√3', '√2', '2', 'Not Defined'],
            ['cot θ', 'Not Defined', '√3', '1', '1/√3', '0'],
          ],
        },
      },
      {
        title: '2. Maximum & Minimum Values of Trigonometric Expressions',
        type: 'formulas',
        content: 'High-speed bounds frequently tested in SSC:',
        mathFormulas: [
          '\\text{Max of } (a\\sin\\theta + b\\cos\\theta) = +\\sqrt{a^2 + b^2}',
          '\\text{Min of } (a\\sin\\theta + b\\cos\\theta) = -\\sqrt{a^2 + b^2}',
          '\\text{Min of } (a\\sin^2\\theta + b\\text{cosec}^2\\theta) = 2\\sqrt{ab} \\quad (a > b)',
          '\\text{Min of } (a\\tan^2\\theta + b\\cot^2\\theta) = 2\\sqrt{ab}',
          '\\text{Min of } (a\\cos^2\\theta + b\\sec^2\\theta) = 2\\sqrt{ab}',
        ],
      },
      {
        title: '3. Heights & Distances: Special Ratio Triangles',
        type: 'rules',
        content: 'Solve height and distance problems in under 15 seconds without trigonometric algebra:',
        rulesList: [
          {
            ruleNo: 1,
            title: '30° - 60° - 90° Triangle Ratio',
            statement: 'The side opposite to 30° is 1, the side opposite to 60° is √3, and the hypotenuse opposite to 90° is 2. Side Ratio = 1 : √3 : 2.',
            incorrect: 'Applying tan 30° and solving cross-multiplications.',
            correct: 'If the height opposite to 30° is h, the shadow opposite to 60° is h√3, and distance is 2h.',
            trapNote: 'Ratio is always 1 (opposite 30°) : √3 (opposite 60°) : 2 (hypotenuse).',
          },
          {
            ruleNo: 2,
            title: '45° - 45° - 90° Triangle Ratio',
            statement: 'The sides opposite to 45° are equal: Side Ratio = 1 : 1 : √2.',
            incorrect: 'Setting up tan 45° equations.',
            correct: 'Height of tower = Length of shadow when elevation angle is 45°.',
            trapNote: 'Hypotenuse = Side × √2.',
          },
        ],
      },
      {
        title: '4. Solved Examples (Step-by-Step)',
        type: 'examples',
        content: 'Worked examples from SSC examinations.',
        solvedExamples: [
          {
            level: 'Moderate',
            question: 'Find the maximum value of (3 sin θ + 4 cos θ).\n(A) 7  (B) 5  (C) 1  (D) √7',
            solution: 'For an expression of the form a sin θ + b cos θ:\nMaximum value = +√(a² + b²)\nHere a = 3 and b = 4.\nMaximum value = √(3² + 4²) = √(9 + 16) = √25 = 5.\nCorrect Answer: (B)',
            fastTrick: 'Pythagorean triplet (3, 4, 5) gives maximum directly as 5.',
          },
        ],
      },
      {
        title: '5. Quick Revision Summary',
        type: 'revision',
        content: '• sin²θ + cos²θ = 1; sec²θ - tan²θ = 1; cosec²θ - cot²θ = 1.\n• a sin θ + b cos θ has max = √(a² + b²) and min = -√(a² + b²).\n• 30°-60°-90° side ratio: 1 : √3 : 2.\n• 45°-45°-90° side ratio: 1 : 1 : √2.',
      },
    ],
  },
];
