import { MCQQuestion } from '../types';

export const MCQ_BANK: MCQQuestion[] = [
  // English - Subject-Verb Agreement
  {
    id: 'q-eng-1',
    subject: 'English',
    topic: 'Subject–Verb Agreement',
    category: 'Grammar',
    difficulty: 'Moderate',
    question: 'Identify the segment in the sentence which contains a grammatical error: "The quality of these freshly picked organic oranges were praised by the committee."',
    options: [
      { id: 'A', text: 'organic oranges were' },
      { id: 'B', text: 'praised by the committee' },
      { id: 'C', text: 'The quality of these' },
      { id: 'D', text: 'freshly picked' },
    ],
    correctAnswer: 'A',
    explanation: 'The head noun of the sentence is "quality", which is singular and uncountable. The plural noun "oranges" is the object of the preposition "of". Therefore, the verb must be singular "was praised", not "were praised".',
    ruleAnchor: 'Rule 1: Prepositional Phrase Interposition',
    sourceType: 'Verified PYQ',
  },
  {
    id: 'q-eng-2',
    subject: 'English',
    topic: 'Subject–Verb Agreement',
    category: 'Grammar',
    difficulty: 'Moderate',
    question: 'Select the option that corrects the underlined segment: "The minister, along with his personal secretaries, have departed for the summit."',
    options: [
      { id: 'A', text: 'has departed for the summit' },
      { id: 'B', text: 'have been departed for the summit' },
      { id: 'C', text: 'are departing for the summit' },
      { id: 'D', text: 'were departed for the summit' },
    ],
    correctAnswer: 'A',
    explanation: 'When two subjects are joined by "along with", the verb agrees with the first subject ("The minister", singular). Hence, "has departed" is correct.',
    ruleAnchor: 'Rule 2: Additive Connectors ("Along with")',
    sourceType: 'Verified PYQ',
  },
  {
    id: 'q-eng-3',
    subject: 'English',
    topic: 'Subject–Verb Agreement',
    category: 'Grammar',
    difficulty: 'Moderate',
    question: 'Fill in the blank: "Neither the manager nor the assistant engineers ______ informed about the structural audit."',
    options: [
      { id: 'A', text: 'was' },
      { id: 'B', text: 'were' },
      { id: 'C', text: 'is' },
      { id: 'D', text: 'has been' },
    ],
    correctAnswer: 'B',
    explanation: 'In correlative "neither...nor", the verb agrees with the nearest subject. "Assistant engineers" is plural and adjacent to the verb, requiring "were".',
    ruleAnchor: 'Rule 3: Correlative Proximity Concord',
    sourceType: 'Verified PYQ',
  },
  {
    id: 'q-eng-4',
    subject: 'English',
    topic: 'Conditionals',
    category: 'Grammar',
    difficulty: 'Challenging',
    question: 'Spot the error: "If she would have prepared thoroughly for the interview, she would have secured the position."',
    options: [
      { id: 'A', text: 'If she would have prepared' },
      { id: 'B', text: 'thoroughly for the interview' },
      { id: 'C', text: 'she would have secured' },
      { id: 'D', text: 'the position' },
    ],
    correctAnswer: 'A',
    explanation: 'In the third conditional (unreal past), the "if" clause takes the Past Perfect (had + V3), never "would have". It should read: "If she had prepared" or "Had she prepared".',
    ruleAnchor: 'Third Conditional & Inversion Rules',
    sourceType: 'Verified PYQ',
  },
  {
    id: 'q-eng-5',
    subject: 'English',
    topic: 'Inversion & Conjunctions',
    category: 'Grammar',
    difficulty: 'Moderate',
    question: 'Choose the grammatically correct sentence:',
    options: [
      { id: 'A', text: 'Hardly had the bell rung than the students rushed out of the classroom.' },
      { id: 'B', text: 'Hardly the bell had rung when the students rushed out of the classroom.' },
      { id: 'C', text: 'Hardly had the bell rung when the students rushed out of the classroom.' },
      { id: 'D', text: 'No sooner had the bell rung when the students rushed out of the classroom.' },
    ],
    correctAnswer: 'C',
    explanation: '"Hardly" takes subject-auxiliary inversion (had + subject + V3) and is always paired with the conjunction "when". ("No sooner" takes "than").',
    ruleAnchor: 'Negative Adverb Inversion',
    sourceType: 'Verified PYQ',
  },
  {
    id: 'q-eng-6',
    subject: 'English',
    topic: 'Prepositions',
    category: 'Exam Grammar',
    difficulty: 'Moderate',
    question: 'Identify the error: "The new residential society comprises of thirty multi-storey buildings."',
    options: [
      { id: 'A', text: 'The new residential society' },
      { id: 'B', text: 'comprises of' },
      { id: 'C', text: 'thirty multi-storey' },
      { id: 'D', text: 'buildings' },
    ],
    correctAnswer: 'B',
    explanation: 'The transitive verb "comprise" means "consist of" and does not take the preposition "of" in the active voice. Correct: "comprises thirty multi-storey buildings".',
    ruleAnchor: 'Fixed Preposition Prohibitions',
    sourceType: 'Verified PYQ',
  },

  // Mathematics - Arithmetic & Geometry
  {
    id: 'q-math-1',
    subject: 'Quantitative',
    topic: 'Percentage',
    category: 'Arithmetic',
    difficulty: 'Easy',
    question: 'If the price of diesel increases by 25%, by what percentage must a transport firm reduce its consumption so that total expenditure remains unchanged?',
    options: [
      { id: 'A', text: '20%' },
      { id: 'B', text: '25%' },
      { id: 'C', text: '16.67%' },
      { id: 'D', text: '22.5%' },
    ],
    correctAnswer: 'A',
    explanation: 'Base shift shortcut: An increase of +1/4 requires a reduction of -1/(4 + 1) = -1/5 = 20% to maintain constant expenditure.',
    formulaAnchor: 'f-delta-pct',
    shortcut: 'Delta: +1/4 -> -1/5 = 20%',
    sourceType: 'Verified PYQ',
  },
  {
    id: 'q-math-2',
    subject: 'Quantitative',
    topic: 'Geometry',
    category: 'Advanced Quant',
    difficulty: 'Moderate',
    question: 'What is the radius of the circle inscribed in a right-angled triangle whose sides are 9 cm, 12 cm, and 15 cm?',
    options: [
      { id: 'A', text: '2 cm' },
      { id: 'B', text: '3 cm' },
      { id: 'C', text: '4 cm' },
      { id: 'D', text: '4.5 cm' },
    ],
    correctAnswer: 'B',
    explanation: 'Inradius in right triangle: r = (a + b - c) / 2 = (9 + 12 - 15) / 2 = 6 / 2 = 3 cm.',
    formulaAnchor: 'f-incircle-right',
    shortcut: 'r = (9 + 12 - 15) / 2 = 3 cm',
    sourceType: 'Verified PYQ',
  },
  {
    id: 'q-math-3',
    subject: 'Quantitative',
    topic: 'Geometry',
    category: 'Advanced Quant',
    difficulty: 'Challenging',
    question: 'In a cyclic quadrilateral ABCD, side AB = 2 cm, BC = 3 cm, CD = 4 cm, and DA = 5 cm. According to Ptolemy’s theorem, what is the product of its diagonals AC × BD?',
    options: [
      { id: 'A', text: '22 cm²' },
      { id: 'B', text: '23 cm²' },
      { id: 'C', text: '25 cm²' },
      { id: 'D', text: '26 cm²' },
    ],
    correctAnswer: 'B',
    explanation: 'Ptolemy’s Theorem states: AC × BD = (AB × CD) + (BC × DA) = (2 × 4) + (3 × 5) = 8 + 15 = 23 cm².',
    formulaAnchor: 'f-ptolemy',
    shortcut: 'Ptolemy: (2 × 4) + (3 × 5) = 23',
    sourceType: 'Verified PYQ',
  },
  {
    id: 'q-math-4',
    subject: 'Quantitative',
    topic: 'Simple & Compound Interest',
    category: 'Arithmetic',
    difficulty: 'Moderate',
    question: 'The difference between Compound Interest and Simple Interest on a certain sum for 2 years at 10% per annum is ₹150. Find the principal sum.',
    options: [
      { id: 'A', text: '₹12,000' },
      { id: 'B', text: '₹15,000' },
      { id: 'C', text: '₹18,000' },
      { id: 'D', text: '₹20,000' },
    ],
    correctAnswer: 'B',
    explanation: 'Difference formula for 2 years: D2 = P × (R / 100)² -> 150 = P × (10 / 100)² = P × (1 / 100) -> P = 150 × 100 = ₹15,000.',
    formulaAnchor: 'f-ci-si-diff-2yr',
    shortcut: 'P = 150 / 0.01 = ₹15,000',
    sourceType: 'Verified PYQ',
  },
  {
    id: 'q-math-5',
    subject: 'Quantitative',
    topic: 'Geometry',
    category: 'Advanced Quant',
    difficulty: 'Moderate',
    question: 'In an equilateral triangle of side 12 cm, find the ratio of the area of its circumcircle to the area of its incircle.',
    options: [
      { id: 'A', text: '2 : 1' },
      { id: 'B', text: '3 : 1' },
      { id: 'C', text: '4 : 1' },
      { id: 'D', text: '8 : 1' },
    ],
    correctAnswer: 'C',
    explanation: 'In any equilateral triangle, the circumradius R is always twice the inradius r (R = 2r). Therefore, Area(Circumcircle) : Area(Incircle) = πR² : πr² = (2)² : (1)² = 4 : 1.',
    formulaAnchor: 'f-equilateral-radii',
    shortcut: 'R = 2r -> Area ratio = 4 : 1 (independent of side length)',
    sourceType: 'Verified PYQ',
  },
  {
    id: 'q-math-6',
    subject: 'Quantitative',
    topic: 'Algebra',
    category: 'Advanced Quant',
    difficulty: 'Challenging',
    question: 'If a + b + c = 0, what is the value of (a³ + b³ + c³) / (3abc)?',
    options: [
      { id: 'A', text: '0' },
      { id: 'B', text: '1' },
      { id: 'C', text: '3' },
      { id: 'D', text: '-1' },
    ],
    correctAnswer: 'B',
    explanation: 'From the algebraic identity a³ + b³ + c³ - 3abc = (a + b + c)(a² + b² + c² - ab - bc - ca). When a + b + c = 0, a³ + b³ + c³ = 3abc. Thus (a³ + b³ + c³) / (3abc) = 1.',
    formulaAnchor: 'f-algebra-cubic',
    shortcut: 'When a + b + c = 0, sum of cubes = 3abc -> Ratio = 1',
    sourceType: 'Verified PYQ',
  },
  // Reasoning - Analogy & Series
  {
    id: 'q-reas-1',
    subject: 'Reasoning',
    topic: 'Analogy',
    category: 'Verbal Reasoning',
    difficulty: 'Moderate',
    question: 'Select the option that is related to the third number in the same way as the second number is related to the first number: 6 : 222 :: 7 : ?',
    options: [
      { id: 'A', text: '343' },
      { id: 'B', text: '350' },
      { id: 'C', text: '336' },
      { id: 'D', text: '352' },
    ],
    correctAnswer: 'B',
    explanation: 'The pattern is n : (n³ + n). For 6: 6³ + 6 = 216 + 6 = 222. For 7: 7³ + 7 = 343 + 7 = 350.',
    ruleAnchor: 'Rule 2: Square & Cube Hierarchy',
    sourceType: 'Verified PYQ',
  },
  {
    id: 'q-reas-2',
    subject: 'Reasoning',
    topic: 'Blood Relations',
    category: 'Verbal Reasoning',
    difficulty: 'Moderate',
    question: 'Pointing towards a photograph, a woman said, "The father of his brother is the only son of my mother." How is the woman related to the man in the photograph?',
    options: [
      { id: 'A', text: 'Mother' },
      { id: 'B', text: 'Aunt' },
      { id: 'C', text: 'Sister' },
      { id: 'D', text: 'Grandmother' },
    ],
    correctAnswer: 'B',
    explanation: '"Only son of my mother" = Woman’s brother. "Father of his brother" = The man’s father. Thus, the man’s father is the woman’s brother, making the woman his Aunt.',
    ruleAnchor: 'Kinship Back-Tracking Method',
    sourceType: 'Verified PYQ',
  },
  {
    id: 'q-reas-3',
    subject: 'Reasoning',
    topic: 'Direction & Distance',
    category: 'Verbal Reasoning',
    difficulty: 'Easy',
    question: 'One morning after sunrise, Suresh was standing facing a pole. The shadow of the pole fell exactly to his right. To which direction was Suresh facing?',
    options: [
      { id: 'A', text: 'South' },
      { id: 'B', text: 'North' },
      { id: 'C', text: 'East' },
      { id: 'D', text: 'West' },
    ],
    correctAnswer: 'A',
    explanation: 'Morning sun rises in the East, so shadows fall toward the West. Since the shadow fell to Suresh’s right, West was on his right side. Hence Suresh was facing South.',
    ruleAnchor: 'Shadow Direction Law',
    sourceType: 'Verified PYQ',
  },
  // General Awareness - Polity & Science
  {
    id: 'q-ga-1',
    subject: 'General Awareness',
    topic: 'Indian Polity',
    category: 'Polity & Constitution',
    difficulty: 'Moderate',
    question: 'Under which Article of the Constitution of India can the Fundamental Rights guaranteed under Articles 20 and 21 NOT be suspended even during a National Emergency?',
    options: [
      { id: 'A', text: 'Article 352' },
      { id: 'B', text: 'Article 356' },
      { id: 'C', text: 'Article 359' },
      { id: 'D', text: 'Article 360' },
    ],
    correctAnswer: 'C',
    explanation: 'By the 44th Amendment Act 1978, Article 359 was amended so that the President cannot suspend the right to move the court for the enforcement of Fundamental Rights guaranteed by Articles 20 and 21.',
    ruleAnchor: 'Art 20 & 21 Non-Derogability',
    sourceType: 'Verified PYQ',
  },
  {
    id: 'q-ga-2',
    subject: 'General Awareness',
    topic: 'General Science',
    category: 'Chemistry',
    difficulty: 'Easy',
    question: 'What is the chemical name and formula of Plaster of Paris (POP)?',
    options: [
      { id: 'A', text: 'Calcium Sulphate Dihydrate (CaSO4 · 2H2O)' },
      { id: 'B', text: 'Calcium Sulphate Hemihydrate (CaSO4 · 1/2 H2O)' },
      { id: 'C', text: 'Calcium Carbonate (CaCO3)' },
      { id: 'D', text: 'Calcium Hydroxide (Ca(OH)2)' },
    ],
    correctAnswer: 'B',
    explanation: 'Plaster of Paris is Calcium Sulphate Hemihydrate (CaSO4 · 1/2 H2O), prepared by heating Gypsum (CaSO4 · 2H2O) to 373 K.',
    ruleAnchor: 'Everyday Chemical Formulas',
    sourceType: 'Verified PYQ',
  },
  {
    id: 'q-ga-3',
    subject: 'General Awareness',
    topic: 'Modern History',
    category: 'Indian History',
    difficulty: 'Moderate',
    question: 'Who among the following was the only session President of the Indian National Congress presided over by Mahatma Gandhi?',
    options: [
      { id: 'A', text: 'Lahore (1929)' },
      { id: 'B', text: 'Belgaum (1924)' },
      { id: 'C', text: 'Calcutta (1920)' },
      { id: 'D', text: 'Karachi (1931)' },
    ],
    correctAnswer: 'B',
    explanation: 'Mahatma Gandhi presided over only one annual session of the Indian National Congress: the 39th session held at Belgaum (Karnataka) in December 1924.',
    ruleAnchor: 'INC Landmark Sessions',
    sourceType: 'Verified PYQ',
  },
  // Tier-II - Statistics & Computer
  {
    id: 'q-t2-1',
    subject: 'Tier-II',
    topic: 'Statistics',
    category: 'Mathematical Abilities',
    difficulty: 'Moderate',
    question: 'If the mean of a moderately skewed distribution is 32 and its median is 35, what is its mode calculated via the empirical relationship?',
    options: [
      { id: 'A', text: '38' },
      { id: 'B', text: '41' },
      { id: 'C', text: '44' },
      { id: 'D', text: '47' },
    ],
    correctAnswer: 'B',
    explanation: 'Empirical formula: Mode = 3·Median - 2·Mean = 3(35) - 2(32) = 105 - 64 = 41.',
    ruleAnchor: 'Empirical Relationship Formula',
    sourceType: 'Verified PYQ',
  },
  {
    id: 'q-t2-2',
    subject: 'Tier-II',
    topic: 'Computer Proficiency',
    category: 'Computer Knowledge',
    difficulty: 'Moderate',
    question: 'Which of the following processor registers holds the memory address of the next sequential instruction to be fetched and executed?',
    options: [
      { id: 'A', text: 'Memory Data Register (MDR)' },
      { id: 'B', text: 'Instruction Register (IR)' },
      { id: 'C', text: 'Program Counter (PC)' },
      { id: 'D', text: 'Accumulator (ACC)' },
    ],
    correctAnswer: 'C',
    explanation: 'The Program Counter (PC) stores the memory location/address of the subsequent instruction awaiting fetch and execution.',
    ruleAnchor: 'CPU Architecture & Registers',
    sourceType: 'Verified PYQ',
  },
];
