import { MockTest, MCQQuestion } from '../types';
import { MCQ_BANK } from './mcqBank';

// Generate verified test questions from bank
const engQuestions25: MCQQuestion[] = [
  ...MCQ_BANK.filter((q) => q.subject === 'English'),
  {
    id: 'q-eng-7',
    subject: 'English',
    topic: 'Pronouns',
    category: 'Grammar',
    difficulty: 'Moderate',
    question: 'Select the option that corrects the pronoun order: "I, you and he must attend the special orientation lecture."',
    options: [
      { id: 'A', text: 'You, he and I must attend' },
      { id: 'B', text: 'He, you and I must attend' },
      { id: 'C', text: 'You, I and he must attend' },
      { id: 'D', text: 'I, he and you must attend' },
    ],
    correctAnswer: 'A',
    explanation: 'In normal/positive contexts, multiple singular personal pronouns follow the 2-3-1 rule (Second Person "You", Third Person "He", First Person "I").',
    ruleAnchor: 'Order of Personal Pronouns (231 rule)',
    sourceType: 'Verified PYQ',
  },
  {
    id: 'q-eng-8',
    subject: 'English',
    topic: 'Nouns',
    category: 'Grammar',
    difficulty: 'Easy',
    question: 'Spot the error: "All the furnitures in the guest house were damaged during the transit."',
    options: [
      { id: 'A', text: 'All the furnitures' },
      { id: 'B', text: 'in the guest house' },
      { id: 'C', text: 'were damaged' },
      { id: 'D', text: 'during the transit' },
    ],
    correctAnswer: 'A',
    explanation: '"Furniture" is an uncountable noun and does not have a plural form. It should be "All the furniture... was damaged".',
    ruleAnchor: 'Uncountable Noun Prohibitions',
    sourceType: 'Verified PYQ',
  },
  {
    id: 'q-eng-9',
    subject: 'English',
    topic: 'Vocabulary',
    category: 'One Word Substitution',
    difficulty: 'Easy',
    question: 'Choose the one-word substitution: "A person who shows selfless concern for the well-being of others."',
    options: [
      { id: 'A', text: 'Egoist' },
      { id: 'B', text: 'Altruist' },
      { id: 'C', text: 'Misanthrope' },
      { id: 'D', text: 'Fatalist' },
    ],
    correctAnswer: 'B',
    explanation: 'An altruist is a person who selflessly cares for and helps others. An egoist cares only for himself.',
    sourceType: 'Verified PYQ',
  },
  {
    id: 'q-eng-10',
    subject: 'English',
    topic: 'Vocabulary',
    category: 'Idioms & Phrases',
    difficulty: 'Moderate',
    question: 'Select the meaning of the idiom: "At one’s wit’s end"',
    options: [
      { id: 'A', text: 'Extremely clever and witty' },
      { id: 'B', text: 'Completely perplexed and not knowing what to do next' },
      { id: 'C', text: 'At the conclusion of a lively debate' },
      { id: 'D', text: 'Seeking financial assistance' },
    ],
    correctAnswer: 'B',
    explanation: '"At one’s wit’s end" means to be so worried, baffled, or exhausted by problems that one does not know what to do next.',
    sourceType: 'Verified PYQ',
  },
];

const mathQuestions25: MCQQuestion[] = [
  ...MCQ_BANK.filter((q) => q.subject === 'Quantitative'),
  {
    id: 'q-math-7',
    subject: 'Quantitative',
    topic: 'Time Speed Distance',
    category: 'Arithmetic',
    difficulty: 'Moderate',
    question: 'Two trains of lengths 140 m and 160 m are running in opposite directions on parallel tracks at 40 km/h and 50 km/h respectively. How long will they take to cross each other?',
    options: [
      { id: 'A', text: '10 seconds' },
      { id: 'B', text: '12 seconds' },
      { id: 'C', text: '14 seconds' },
      { id: 'D', text: '15 seconds' },
    ],
    correctAnswer: 'B',
    explanation: 'Total distance = 140 + 160 = 300 m. Relative speed in opposite directions = 40 + 50 = 90 km/h = 90 × (5/18) = 25 m/s. Time = 300 / 25 = 12 seconds.',
    formulaAnchor: 'f-speed-relative',
    shortcut: 'Time = 300 m / (90 × 5/18 m/s) = 300 / 25 = 12 s',
    sourceType: 'Verified PYQ',
  },
  {
    id: 'q-math-8',
    subject: 'Quantitative',
    topic: 'Trigonometry',
    category: 'Advanced Quant',
    difficulty: 'Moderate',
    question: 'If sec θ + tan θ = 3, find the value of cos θ.',
    options: [
      { id: 'A', text: '3/5' },
      { id: 'B', text: '4/5' },
      { id: 'C', text: '5/3' },
      { id: 'D', text: '3/4' },
    ],
    correctAnswer: 'A',
    explanation: 'Since sec²θ - tan²θ = 1, sec θ - tan θ = 1/3. Adding the two equations: 2 sec θ = 3 + 1/3 = 10/3 -> sec θ = 5/3. Hence cos θ = 1 / sec θ = 3/5.',
    formulaAnchor: 'f-trig-pythagorean',
    shortcut: 'sec θ = (3 + 1/3) / 2 = 5/3 -> cos θ = 3/5',
    sourceType: 'Verified PYQ',
  },
  {
    id: 'q-math-9',
    subject: 'Quantitative',
    topic: 'Mensuration 2D',
    category: 'Advanced Quant',
    difficulty: 'Easy',
    question: 'The diagonals of a rhombus are 16 cm and 12 cm. What is the perimeter of the rhombus?',
    options: [
      { id: 'A', text: '36 cm' },
      { id: 'B', text: '40 cm' },
      { id: 'C', text: '48 cm' },
      { id: 'D', text: '52 cm' },
    ],
    correctAnswer: 'B',
    explanation: 'The diagonals bisect at right angles. Half diagonals are 8 cm and 6 cm. Side = √(8² + 6²) = √(64 + 36) = √100 = 10 cm. Perimeter = 4 × 10 = 40 cm.',
    shortcut: 'Triplet 6-8-10 -> Side = 10 -> Perimeter = 40 cm',
    sourceType: 'Verified PYQ',
  },
  {
    id: 'q-math-10',
    subject: 'Quantitative',
    topic: 'Percentage',
    category: 'Arithmetic',
    difficulty: 'Moderate',
    question: 'Two successive discounts of 20% and 10% are equivalent to a single discount of:',
    options: [
      { id: 'A', text: '30%' },
      { id: 'B', text: '28%' },
      { id: 'C', text: '25%' },
      { id: 'D', text: '26%' },
    ],
    correctAnswer: 'B',
    explanation: 'Single equivalent discount = d1 + d2 - (d1 × d2)/100 = 20 + 10 - (200/100) = 30 - 2 = 28%.',
    formulaAnchor: 'f-successive-pct',
    shortcut: '20 + 10 - 2 = 28%',
    sourceType: 'Verified PYQ',
  },
];

export const MOCK_TESTS: MockTest[] = [
  // Sectional Mock Tests (25 Qs, 15 Mins, 50 Marks)
  {
    id: 'eng-sec-1',
    title: 'English Sectional Mock 1',
    subject: 'English',
    type: 'Sectional',
    questionsCount: engQuestions25.length,
    durationMinutes: 15,
    maxMarks: 50,
    description: 'Tier-I TCS Exam Pattern covering Subject-Verb Concord, Tenses, Correlatives, and BlackBook Vocabulary.',
    sections: [
      {
        sectionId: 'sec-eng-1',
        sectionName: 'English Comprehension & Language',
        subject: 'English',
        questionsCount: engQuestions25.length,
        durationMinutes: 15,
        questions: engQuestions25,
      },
    ],
  },
  {
    id: 'eng-sec-2',
    title: 'English Sectional Mock 2',
    subject: 'English',
    type: 'Sectional',
    questionsCount: engQuestions25.length,
    durationMinutes: 15,
    maxMarks: 50,
    description: 'Speed-focused Tier-I drill testing Conditionals, Prepositions, Spotting Errors, and Idioms.',
    sections: [
      {
        sectionId: 'sec-eng-2',
        sectionName: 'English Comprehension & Language',
        subject: 'English',
        questionsCount: engQuestions25.length,
        durationMinutes: 15,
        questions: engQuestions25,
      },
    ],
  },
  {
    id: 'eng-sec-3',
    title: 'English Sectional Mock 3',
    subject: 'English',
    type: 'Sectional',
    questionsCount: engQuestions25.length,
    durationMinutes: 15,
    maxMarks: 50,
    description: 'High-difficulty mock featuring inversion traps, active-passive voice shifts, and sentence improvement.',
    sections: [
      {
        sectionId: 'sec-eng-3',
        sectionName: 'English Comprehension & Language',
        subject: 'English',
        questionsCount: engQuestions25.length,
        durationMinutes: 15,
        questions: engQuestions25,
      },
    ],
  },

  // Maths Sectional Mock Tests (25 Qs, 15 Mins, 50 Marks)
  {
    id: 'math-sec-1',
    title: 'Maths Sectional Mock 1',
    subject: 'Quantitative',
    type: 'Sectional',
    questionsCount: mathQuestions25.length,
    durationMinutes: 15,
    maxMarks: 50,
    description: 'Tier-I Quantitative Aptitude mock with percentage delta shortcuts, geometry inradius, and relative speed.',
    sections: [
      {
        sectionId: 'sec-math-1',
        sectionName: 'Quantitative Aptitude',
        subject: 'Quantitative',
        questionsCount: mathQuestions25.length,
        durationMinutes: 15,
        questions: mathQuestions25,
      },
    ],
  },
  {
    id: 'math-sec-2',
    title: 'Maths Sectional Mock 2',
    subject: 'Quantitative',
    type: 'Sectional',
    questionsCount: mathQuestions25.length,
    durationMinutes: 15,
    maxMarks: 50,
    description: 'Advanced Quant focus: Ptolemy theorem, cyclic quadrilaterals, CI-SI 2-year differences, and trigonometry.',
    sections: [
      {
        sectionId: 'sec-math-2',
        sectionName: 'Quantitative Aptitude',
        subject: 'Quantitative',
        questionsCount: mathQuestions25.length,
        durationMinutes: 15,
        questions: mathQuestions25,
      },
    ],
  },
  {
    id: 'math-sec-3',
    title: 'Maths Sectional Mock 3',
    subject: 'Quantitative',
    type: 'Sectional',
    questionsCount: mathQuestions25.length,
    durationMinutes: 15,
    maxMarks: 50,
    description: 'Calculative arithmetic and algebraic cubic identities. Tests speed under strict 15-minute timer.',
    sections: [
      {
        sectionId: 'sec-math-3',
        sectionName: 'Quantitative Aptitude',
        subject: 'Quantitative',
        questionsCount: mathQuestions25.length,
        durationMinutes: 15,
        questions: mathQuestions25,
      },
    ],
  },

  // Daily Mini Tests 1-5 (10 Qs, 8 Mins)
  ...[1, 2, 3, 4, 5].map((num) => ({
    id: `mini-test-${num}`,
    title: `Daily Mini Test ${num}`,
    subject: (num % 2 === 1 ? 'English' : 'Quantitative') as 'English' | 'Quantitative',
    type: 'Daily Mini' as const,
    questionsCount: 6,
    durationMinutes: 8,
    maxMarks: 12,
    description: `Daily 8-minute rapid precision check for academic streak maintenance.`,
    sections: [
      {
        sectionId: `sec-mini-${num}`,
        sectionName: num % 2 === 1 ? 'English Daily Sprint' : 'Quantitative Daily Sprint',
        subject: (num % 2 === 1 ? 'English' : 'Quantitative') as 'English' | 'Quantitative',
        questionsCount: 6,
        durationMinutes: 8,
        questions: num % 2 === 1 ? engQuestions25.slice(0, 6) : mathQuestions25.slice(0, 6),
      },
    ],
  })),

  // Final Revision Test (Combined English + Maths, 50 Qs, 30 Mins, 100 Marks)
  {
    id: 'final-revision-test',
    title: 'Final English + Maths Revision Test',
    subject: 'Combined',
    type: 'Final Revision',
    questionsCount: engQuestions25.length + mathQuestions25.length,
    durationMinutes: 30,
    maxMarks: 100,
    description: 'Full-scale sectional simulation with two distinct 15-minute section timers. Time does NOT transfer across sections.',
    sections: [
      {
        sectionId: 'sec-final-eng',
        sectionName: 'Section 1: English Language',
        subject: 'English',
        questionsCount: engQuestions25.length,
        durationMinutes: 15,
        questions: engQuestions25,
      },
      {
        sectionId: 'sec-final-math',
        sectionName: 'Section 2: Quantitative Aptitude',
        subject: 'Quantitative',
        questionsCount: mathQuestions25.length,
        durationMinutes: 15,
        questions: mathQuestions25,
      },
    ],
  },
];
