import { StudyChapter } from '../types';

export const TIER2_CHAPTERS: StudyChapter[] = [
  {
    slug: 'statistics-tier2',
    title: 'Statistics: Mean, Median, Mode, Variance & Std Deviation',
    subject: 'Tier-II',
    unit: 'Module 1: Mathematical Abilities (Tier-II)',
    category: 'Statistics & Probability',
    subcategory: 'Measures of Central Tendency & Dispersion',
    priority: 'High Priority',
    tier: 'Tier-II',
    estimatedMinutes: 45,
    rulesCount: 10,
    mcqsCount: 25,
    wordCount: 1650,
    summary: 'Mastering arithmetic mean, grouped/ungrouped median, empirical relationship (Mode = 3 Median - 2 Mean), variance, and standard deviation.',
    order: 1,
    nextSlug: 'probability-tier2',
    favouriteTrap: 'Confusing Variance (σ²) with Standard Deviation (σ = √Variance). Always verify which metric the question asks for.',
    memoryTrick: 'Empirical Relationship: Mode = 3 Median - 2 Mean ("Three Medians minus Two Means equals Mode").',
    sections: [
      {
        title: '1. Introduction & Tier-II Mandate',
        type: 'intro',
        content: 'Since the revised SSC CGL examination scheme, Statistics and Probability are compulsory topics in Tier-II Paper-I (Section-I: Mathematical Abilities), accounting for 3 to 5 questions (9 to 15 marks). Candidates are evaluated on computation of central tendencies, dispersion metrics, and empirical frequency distributions.',
      },
      {
        title: '2. Core Formulas of Central Tendency & Dispersion',
        type: 'formulas',
        content: 'Formulas required for Tier-II calculations:',
        mathFormulas: [
          'Arithmetic Mean (Ungrouped): x̄ = (∑x_i) / n',
          'Arithmetic Mean (Grouped): x̄ = (∑f_i · x_i) / (∑f_i)',
          'Median (Ungrouped Odd n): Value of ((n + 1) / 2)-th term in sorted data',
          'Median (Ungrouped Even n): Average of (n/2)-th and ((n/2) + 1)-th terms',
          'Median (Grouped Continuous Data): Median = L + [ ((n/2) - cf) / f ] × h',
          'Mode (Grouped Continuous Data): Mode = L + [ (f1 - f0) / (2f1 - f0 - f2) ] × h',
          'Empirical Formula for Moderately Skewed Data: Mode = 3·Median - 2·Mean',
          'Population Variance (σ²): σ² = [∑(x_i - x̄)²] / n = [∑x_i² / n] - (x̄)²',
          'Standard Deviation (σ): σ = √Variance = √[ (∑(x_i - x̄)²) / n ]',
          'Coefficient of Variation (C.V.): C.V. = (σ / x̄) × 100%',
        ],
      },
      {
        title: '3. Essential Rules & Arithmetic Properties',
        type: 'rules',
        content: 'Rules that allow solving Tier-II problems in under 20 seconds:',
        rulesList: [
          {
            ruleNo: 1,
            title: 'Linear Shift on Mean vs Standard Deviation',
            statement: 'If every observation in a dataset is increased/decreased by a constant k:\n• New Mean = Old Mean ± k\n• New Variance = Old Variance (UNCHANGED!)\n• New Standard Deviation = Old Standard Deviation (UNCHANGED!)\nDispersion is completely invariant under origin shift.',
            incorrect: 'Adding k to the standard deviation or variance.',
            correct: 'Standard deviation depends only on spread from mean; adding k shifts the entire distribution without widening it.',
            trapNote: 'Variance and Standard Deviation DO NOT change when a constant is added to all numbers.',
          },
          {
            ruleNo: 2,
            title: 'Linear Scaling on Dispersion',
            statement: 'If every observation in a dataset is multiplied by a positive constant k:\n• New Mean = k × Old Mean\n• New Standard Deviation = k × Old Standard Deviation\n• New Variance = k² × Old Variance.',
            incorrect: 'Multiplying variance by k instead of k².',
            correct: 'Variance squares the multiplier: if data is multiplied by 3, variance is multiplied by 9.',
            trapNote: 'Standard deviation is multiplied by |k|; variance is multiplied by k².',
          },
        ],
      },
      {
        title: '4. Solved Examples (Step-by-Step)',
        type: 'examples',
        content: 'Step-by-step solved problems based on recent Tier-II exams.',
        solvedExamples: [
          {
            level: 'SSC-level',
            question: 'If the mean of a moderately skewed distribution is 32 and its median is 35, calculate its mode using the empirical relationship.\n(A) 38  (B) 41  (C) 44  (D) 47',
            solution: 'Use the standard Empirical Relationship formula:\nMode = 3·Median - 2·Mean\nSubstitute the given values:\nMode = 3 × 35 - 2 × 32\nMode = 105 - 64\nMode = 41\nCorrect Answer: (B)',
            fastTrick: 'Direct substitution into Mode = 3·Median - 2·Mean.',
          },
          {
            level: 'SSC-level',
            question: 'Find the standard deviation of the first five prime numbers: 2, 3, 5, 7, 11.\n(A) √10.24  (B) 3.2  (C) √10.16  (D) 3.4',
            solution: 'Step 1: Calculate the Mean (x̄):\nx̄ = (2 + 3 + 5 + 7 + 11) / 5 = 28 / 5 = 5.6\n\nStep 2: Calculate squared deviations (x_i - x̄)²:\n(2 - 5.6)² = (-3.6)² = 12.96\n(3 - 5.6)² = (-2.6)² = 6.76\n(5 - 5.6)² = (-0.6)² = 0.36\n(7 - 5.6)² = (1.4)² = 1.96\n(11 - 5.6)² = (5.4)² = 29.16\n\nStep 3: Sum the squared deviations:\n∑(x_i - x̄)² = 12.96 + 6.76 + 0.36 + 1.96 + 29.16 = 51.2\n\nStep 4: Variance σ² = 51.2 / 5 = 10.24\n\nStep 5: Standard Deviation σ = √10.24 = 3.2\nCorrect Answer: (B)',
            fastTrick: '√10.24 = 3.2 since 32² = 1024.',
          },
        ],
      },
      {
        title: '5. Practice Questions',
        type: 'practice',
        content: 'Solve and test your speed on Tier-II statistics.',
        practiceQuestions: [
          {
            id: 'stat-p-1',
            question: 'If the variance of a data set is 81 and each observation is multiplied by 2, what will be the new variance?',
            options: ['162', '324', '81', '729'],
            correctIndex: 1,
            explanation: 'When each observation is multiplied by k, the new variance becomes k² × (Old Variance). Here k = 2, so New Variance = 2² × 81 = 4 × 81 = 324.',
            sourceType: 'PYQ-style',
          },
        ],
      },
      {
        title: '6. Quick Revision Summary',
        type: 'revision',
        content: '• Mode = 3 Median - 2 Mean.\n• Standard Deviation is the positive square root of Variance (σ = √Variance).\n• Adding a constant to all data points leaves Variance & SD unchanged.\n• Multiplying all data points by k multiplies SD by k, and Variance by k².\n• Coefficient of Variation (C.V.) = (σ / Mean) × 100%. Lower C.V. indicates higher consistency/stability.',
      },
    ],
  },
  {
    slug: 'probability-tier2',
    title: 'Probability: Basic Laws, Combinations & Conditional Probability',
    subject: 'Tier-II',
    unit: 'Module 1: Mathematical Abilities (Tier-II)',
    category: 'Statistics & Probability',
    subcategory: 'Chance & Stochastic Events',
    priority: 'High Priority',
    tier: 'Tier-II',
    estimatedMinutes: 40,
    rulesCount: 8,
    mcqsCount: 25,
    wordCount: 1550,
    summary: 'Classical probability definition, card deck calculations, coin tosses, dice rolls, addition & multiplication theorems, and mutually exclusive events.',
    order: 2,
    nextSlug: 'computer-proficiency-module',
    favouriteTrap: 'Confusing Mutually Exclusive events [P(A ∩ B) = 0] with Independent events [P(A ∩ B) = P(A) × P(B)].',
    memoryTrick: 'P(At least one) = 1 - P(None). This single shortcut solves 70% of multi-coin, multi-die, and target-hitting questions.',
    sections: [
      {
        title: '1. Introduction & Exam Scope',
        type: 'intro',
        content: 'Probability is a dedicated module in SSC CGL Tier-II Paper-I. Questions test combinations (nCr), coin toss sequences, 2-dice permutations, 52-card standard deck selections, and non-overlapping events.',
      },
      {
        title: '2. Standard Sample Spaces Reference',
        type: 'concept',
        content: 'Quick reference for recurring sample spaces:\n• Coins: Tossing n fair coins has total outcomes = 2^n. For 3 coins: 2³ = 8 outcomes (HHH, HHT, HTH, HTT, THH, THT, TTH, TTT).\n• Dice: Rolling n six-sided dice has total outcomes = 6^n. For 2 dice: 6² = 36 outcomes. Sum of two dice ranges from 2 to 12. Most frequent sum is 7 (6 ways: 1+6, 2+5, 3+4, 4+3, 5+2, 6+1; P(Sum 7) = 6/36 = 1/6).\n• Playing Cards: Standard deck has 52 cards, divided into 4 Suits of 13 cards each:\n  - 2 Red Suits (26 cards): Hearts (13), Diamonds (13)\n  - 2 Black Suits (26 cards): Spades (13), Clubs (13)\n  - Face / Court Cards (12 cards): 4 Kings, 4 Queens, 4 Jacks\n  - Honor Cards (16 cards): 4 Aces + 12 Face Cards\n  - Numbered Cards (36 cards): 2 through 10 in each of 4 suits.',
      },
      {
        title: '3. Fundamental Theorems & Addition / Multiplication Laws',
        type: 'formulas',
        content: 'Core probability theorems tested in SSC:',
        mathFormulas: [
          'Classical Probability: P(E) = n(E) / n(S) = (Favourable Outcomes) / (Total Outcomes)',
          'Complementary Probability: P(E\') = 1 - P(E)',
          'Range of Probability: 0 ≤ P(E) ≤ 1 (P = 0 is Impossible event; P = 1 is Certain event)',
          'Addition Theorem (General): P(A ∪ B) = P(A) + P(B) - P(A ∩ B)',
          'Addition Theorem (Mutually Exclusive): P(A ∩ B) = 0 ⟹ P(A ∪ B) = P(A) + P(B)',
          'Multiplication Theorem (Independent Events): P(A ∩ B) = P(A) × P(B)',
          'Conditional Probability: P(A | B) = P(A ∩ B) / P(B), where P(B) > 0',
          'At Least One Event: P(At least one success) = 1 - P(Zero successes)',
        ],
      },
      {
        title: '4. Solved Examples (Step-by-Step)',
        type: 'examples',
        content: 'Worked problems from SSC Tier-II standard.',
        solvedExamples: [
          {
            level: 'Moderate',
            question: 'Two dice are thrown simultaneously. What is the probability of getting a sum divisible by 5?\n(A) 1/6  (B) 7/36  (C) 1/4  (D) 5/36',
            solution: 'Total outcomes when throwing 2 dice = 6 × 6 = 36.\nPossible sums divisible by 5 between 2 and 12 are 5 and 10:\n• Outcomes giving Sum = 5: (1, 4), (2, 3), (3, 2), (4, 1) → 4 pairs\n• Outcomes giving Sum = 10: (4, 6), (5, 5), (6, 4) → 3 pairs\nTotal favourable outcomes = 4 + 3 = 7.\nProbability = Favourable / Total = 7 / 36.\nCorrect Answer: (B)',
            fastTrick: 'Enumerate pairs for sum 5 (4 ways) and sum 10 (3 ways) → 7/36.',
          },
          {
            level: 'SSC-level',
            question: 'A card is drawn at random from a well-shuffled pack of 52 cards. What is the probability that the card drawn is either a King or a Heart?\n(A) 4/13  (B) 17/52  (C) 16/52  (D) 1/4',
            solution: 'Apply the General Addition Theorem:\nP(King ∪ Heart) = P(King) + P(Heart) - P(King ∩ Heart)\n• Total Cards = 52\n• Number of Kings = 4 ⟹ P(King) = 4/52\n• Number of Hearts = 13 ⟹ P(Heart) = 13/52\n• Number of Kings of Hearts (Intersection) = 1 ⟹ P(King ∩ Heart) = 1/52\n\nSubstitute into the formula:\nP(King ∪ Heart) = (4/52) + (13/52) - (1/52) = (4 + 13 - 1) / 52 = 16 / 52 = 4 / 13.\nCorrect Answer: (A)',
            fastTrick: '13 Hearts + 3 remaining Kings = 16 cards total. 16/52 = 4/13.',
            trapNote: 'Do not count the King of Hearts twice!',
          },
        ],
      },
      {
        title: '5. Practice Questions',
        type: 'practice',
        content: 'Solve to verify your mastery.',
        practiceQuestions: [
          {
            id: 'prb-p-1',
            question: 'Three unbiased coins are tossed together. What is the probability of getting at least two heads?',
            options: ['1/2', '3/8', '5/8', '7/8'],
            correctIndex: 0,
            explanation: 'Total outcomes = 2³ = 8. At least two heads means 2 Heads or 3 Heads: {HHT, HTH, THH, HHH} = 4 favourable outcomes. Probability = 4/8 = 1/2.',
            sourceType: 'PYQ-style',
          },
        ],
      },
      {
        title: '6. Quick Revision Summary',
        type: 'revision',
        content: '• P(At least one) = 1 - P(None).\n• For independent events: P(A and B) = P(A) × P(B).\n• For mutually exclusive events: P(A and B) = 0.\n• Sum of two dice: Minimum sum = 2 (1 way), Peak sum = 7 (6 ways), Maximum sum = 12 (1 way).\n• 52-card deck has 12 Face Cards (4 Kings, 4 Queens, 4 Jacks).',
      },
    ],
  },
  {
    slug: 'computer-proficiency-module',
    title: 'Computer Knowledge Module: Hardware, Software, Networking & MS Office',
    subject: 'Tier-II',
    unit: 'Module 2: Computer Knowledge (Tier-II Qualifying)',
    category: 'Computer Proficiency',
    subcategory: 'Hardware, OS, Networking & Security',
    priority: 'High Priority',
    tier: 'Tier-II',
    estimatedMinutes: 50,
    rulesCount: 15,
    mcqsCount: 40,
    wordCount: 1950,
    summary: 'CPU organization, memory hierarchy (Registers, Cache, RAM, ROM, SSD), Windows OS, MS Word & Excel shortcuts, networking protocols (TCP/IP, HTTP, DNS), and Cyber Security.',
    order: 3,
    favouriteTrap: 'Failing the Computer Knowledge Module disqualifies the candidate from Tier-II selection regardless of scoring 350+ marks in Section-I and II. It is mandatory qualifying (min 18 marks out of 60).',
    memoryTrick: 'Memory Hierarchy Speed: CPU Registers > L1 Cache > L2 Cache > L3 Cache > RAM (DRAM) > SSD > HDD. Faster = Smaller & More Expensive.',
    sections: [
      {
        title: '1. Introduction & Mandatory Qualifying Rules',
        type: 'intro',
        content: 'The Computer Knowledge Test (Module-I of Section-III in Paper-I) comprises 20 questions of 3 marks each (Total: 60 marks, 15 minutes duration). It is MANDATORY QUALIFYING in nature with 1 negative mark for each wrong answer. While qualifying for all posts (UR: 30% = 18 marks, OBC/EWS: 25% = 15 marks, SC/ST: 20% = 12 marks), higher cut-offs are applied for posts like ASO in CSS/MEA, Inspector of Central Excise, Preventive Officer, and Examiner.',
      },
      {
        title: '2. Computer Organization & Memory Hierarchy Table',
        type: 'concept',
        content: 'Core architecture and storage stratification tested in SSC:',
        table: {
          title: 'Memory Hierarchy & Storage Taxonomy',
          headers: ['Memory Tier', 'Nature / Technology', 'Speed & Latency', 'Volatility & Characteristics'],
          rows: [
            ['CPU Registers', 'Static Flip-Flops inside CPU core (MAR, MBR, PC, IR, Accumulator)', 'Fastest (< 1 ns)', 'Volatile; stores active operands for immediate ALU execution.'],
            ['Cache Memory (L1, L2, L3)', 'SRAM (Static RAM, does NOT require periodic refresh)', 'Very Fast (1 - 10 ns)', 'Volatile; bridges speed mismatch between CPU and primary memory.'],
            ['Main Memory (RAM)', 'DRAM (Dynamic RAM, requires continuous capacitor refresh)', 'Fast (20 - 50 ns)', 'Volatile; directly byte-addressable by CPU; holds OS kernel and open programs.'],
            ['Read Only Memory (ROM)', 'PROM, EPROM (UV erasable), EEPROM (Electrically erasable, Flash)', 'Moderate', 'NON-VOLATILE; stores BIOS / UEFI firmware and Power-On Self-Test (POST) code.'],
            ['Solid State Drive (SSD)', 'NAND Flash Memory (No moving mechanical parts)', 'Moderate to Fast (500 - 7000 MB/s)', 'Non-volatile; high endurance, silent, low latency compared to magnetic disks.'],
            ['Hard Disk Drive (HDD)', 'Magnetic platters with read/write heads (RPM: 5400/7200)', 'Slow (80 - 200 MB/s)', 'Non-volatile; mechanical seek time latency; high bulk storage capacity.'],
          ],
        },
      },
      {
        title: '3. Master MS Office Shortcuts Table (Word & Excel)',
        type: 'concept',
        content: 'Shortcuts tested repeatedly in Tier-II computer questions:',
        table: {
          title: 'Essential Keyboard Shortcuts for MS Word & MS Excel',
          headers: ['Shortcut Key', 'Application', 'Precise Function Executed'],
          rows: [
            ['Ctrl + F2', 'MS Word & Excel', 'Displays Print Preview window.'],
            ['F4', 'MS Excel', 'Toggles cell reference between Relative (A1) and Absolute ($A$1). In Word: Repeats last action.'],
            ['F7', 'MS Office', 'Launches Spelling and Grammar check dialog.'],
            ['Shift + F7', 'MS Word', 'Opens the Research task pane / Thesaurus.'],
            ['F12', 'MS Office', 'Opens the "Save As" dialog box directly.'],
            ['Ctrl + Enter', 'MS Word', 'Inserts a Page Break at the current cursor location.'],
            ['Shift + Enter', 'MS Word', 'Inserts a Soft Line Break (Line Break without starting a new paragraph).'],
            ['Ctrl + K', 'MS Office', 'Inserts a Hyperlink.'],
            ['Ctrl + H', 'MS Office', 'Opens the "Find and Replace" dialog box.'],
            ['Ctrl + E', 'MS Word', 'Aligns the selected paragraph to Center.'],
            ['Ctrl + J', 'MS Word', 'Justifies the selected paragraph.'],
            ['Ctrl + M', 'MS Word', 'Indents paragraph from the left margin.'],
            ['Ctrl + 1', 'MS Excel', 'Opens the "Format Cells" dialog box.'],
            ['Ctrl + Shift + L', 'MS Excel', 'Applies or removes AutoFilter on the selected data range.'],
            ['Alt + = (Equals)', 'MS Excel', 'Inserts the AutoSum formula: =SUM(...) automatically.'],
            ['Ctrl + ; (Semicolon)', 'MS Excel', 'Inserts the current System Date into the active cell.'],
            ['Ctrl + Shift + : (Colon)', 'MS Excel', 'Inserts the current System Time into the active cell.'],
          ],
        },
      },
      {
        title: '4. Networking Protocols & Port Numbers Table',
        type: 'concept',
        content: 'Protocols governing the Internet and data transport:',
        table: {
          title: 'Networking Protocols, Layers and Default Port Numbers',
          headers: ['Protocol', 'Full Name', 'OSI Layer', 'Default Port & Function'],
          rows: [
            ['HTTP', 'HyperText Transfer Protocol', 'Application (Layer 7)', 'Port 80; Unencrypted web page transmission.'],
            ['HTTPS', 'HyperText Transfer Protocol Secure', 'Application (Layer 7)', 'Port 443; Encrypted web transmission using TLS/SSL.'],
            ['FTP', 'File Transfer Protocol', 'Application (Layer 7)', 'Port 20 (Data Transfer) & Port 21 (Control/Commands).'],
            ['SSH', 'Secure Shell', 'Application (Layer 7)', 'Port 22; Secure remote command-line login and tunnel.'],
            ['Telnet', 'Teletype Network', 'Application (Layer 7)', 'Port 23; Unencrypted, insecure remote terminal emulation.'],
            ['SMTP', 'Simple Mail Transfer Protocol', 'Application (Layer 7)', 'Port 25 (or 587); PUSH protocol used to SEND emails.'],
            ['POP3', 'Post Office Protocol version 3', 'Application (Layer 7)', 'Port 110 (or 995 SSL); PULL protocol used to DOWNLOAD emails locally.'],
            ['IMAP', 'Internet Message Access Protocol', 'Application (Layer 7)', 'Port 143 (or 993 SSL); PULL protocol used to SYNC emails across multiple devices.'],
            ['DNS', 'Domain Name System', 'Application (Layer 7)', 'Port 53 (uses UDP & TCP); Translates domain names into IP addresses.'],
            ['DHCP', 'Dynamic Host Configuration Protocol', 'Application (Layer 7)', 'Port 67 (Server) & 68 (Client); Dynamically assigns IP addresses to hosts.'],
          ],
        },
      },
      {
        title: '5. Solved Examples (Tier-II Standard)',
        type: 'examples',
        content: 'Authentic Tier-II questions with technical rationale.',
        solvedExamples: [
          {
            level: 'SSC-level',
            question: 'Which of the following registers inside the CPU holds the memory address of the next instruction to be fetched and executed?\n(A) Memory Data Register (MDR)\n(B) Instruction Register (IR)\n(C) Program Counter (PC)\n(D) Accumulator (ACC)',
            solution: 'The Program Counter (PC), also known as the Instruction Pointer (IP), is a dedicated processor register that holds the memory address of the next sequential instruction awaiting retrieval from memory. Once the instruction is fetched, the PC automatically increments to point to the subsequent memory address.\nCorrect Answer: (C)',
            fastTrick: 'PC = Next instruction address.',
          },
          {
            level: 'SSC-level',
            question: 'In MS Excel, what is the keyboard shortcut to make a cell reference absolute (e.g. changing A1 to $A$1)?\n(A) F2  (B) F4  (C) F7  (D) F11',
            solution: 'In MS Excel, while editing a formula in the formula bar or cell, pressing the F4 key cycles through all four cell reference modes:\n1. Absolute Column & Absolute Row: $A$1\n2. Relative Column & Absolute Row: A$1\n3. Absolute Column & Relative Row: $A1\n4. Relative Column & Relative Row: A1\nCorrect Answer: (B)',
            fastTrick: 'F4 toggles the dollar ($) sign for absolute referencing.',
          },
        ],
      },
      {
        title: '6. Practice Questions',
        type: 'practice',
        content: 'Check your computer proficiency.',
        practiceQuestions: [
          {
            id: 'cmp-p-1',
            question: 'Which among the following types of malware is designed to record every keystroke pressed by a user on a keyboard to steal passwords and sensitive financial credentials?',
            options: ['Ransomware', 'Keylogger', 'Trojan Horse', 'Rootkit'],
            correctIndex: 1,
            explanation: 'A Keylogger (Keystroke Logger) is a surveillance malware tool that covertly monitors and logs all user keystrokes into a hidden file, which is then transmitted to the attacker to capture passwords, credit card numbers, and confidential messages.',
            sourceType: 'PYQ-style',
          },
        ],
      },
      {
        title: '7. Quick Revision Summary',
        type: 'revision',
        content: '• CPU Registers are the fastest and smallest memory tier.\n• SRAM is used for Cache Memory; DRAM is used for main RAM.\n• BIOS is stored in ROM (non-volatile).\n• SMTP is for SENDING email; POP3 and IMAP are for RECEIVING email.\n• In MS Excel: Alt + = is AutoSum; Ctrl + ; inserts current date; F4 toggles absolute reference ($).\n• Minimum qualifying score for Computer module is 18/60 (30% for UR).',
      },
    ],
  },
];
