import { VocabItem } from '../types';

export const VOCABULARY_DATA: VocabItem[] = [
  // One Word Substitution
  {
    id: 'v-ows-1',
    word: 'Altruist',
    meaning: 'A person who shows selfless concern for the well-being of others.',
    type: 'one-word',
    category: 'Human Character & Philosophy',
    example: 'Her mother was a dedicated altruist who spent decades establishing free clinics.',
    synonyms: ['Philanthropist', 'Benefactor', 'Humanitarian'],
    antonyms: ['Egoist', 'Misanthrope'],
    mnemonic: 'Altruist = "Alter" (other) + "ist" (one who does) -> One who cares for others.',
  },
  {
    id: 'v-ows-2',
    word: 'Ephemeral',
    meaning: 'Lasting for a very short time; transitory and fleeting.',
    type: 'one-word',
    category: 'Time & Existence',
    example: 'The beauty of the morning mist over the valley was purely ephemeral.',
    synonyms: ['Evanescent', 'Transient', 'Fleeting', 'Momentary'],
    antonyms: ['Eternal', 'Permanent', 'Perpetual'],
    mnemonic: 'Ephemeral sounds like "E-funeral" -> brief like the passing moments of life.',
  },
  {
    id: 'v-ows-3',
    word: 'Fastidious',
    meaning: 'Very attentive to and concerned about accuracy and detail; difficult to please.',
    type: 'one-word',
    category: 'Personality & Mannerism',
    example: 'He is so fastidious about grammar that he proofreads every email five times.',
    synonyms: ['Meticulous', 'Punctilious', 'Fussy', 'Perfectionist'],
    antonyms: ['Careless', 'Sloppy', 'Lenient'],
    mnemonic: 'Fastidious = Fast + Tidy -> very fussy about keeping things tidy.',
  },
  {
    id: 'v-ows-4',
    word: 'Incorrigible',
    meaning: 'Not able to be corrected, improved, or reformed.',
    type: 'one-word',
    category: 'Behavior & Conduct',
    example: 'The habitual gambler proved to be an incorrigible risk-taker.',
    synonyms: ['Unreformable', 'Incurable', 'Inveterate', 'Irredeemable'],
    antonyms: ['Reformable', 'Repentant', 'Docile'],
    mnemonic: 'In (not) + corrigible (correctable) -> Cannot be corrected.',
  },
  {
    id: 'v-ows-5',
    word: 'Omniscient',
    meaning: 'Knowing everything; having infinite knowledge.',
    type: 'one-word',
    category: 'Qualities & Attributes',
    example: 'In classical literature, the third-person narrator is often omniscient.',
    synonyms: ['All-knowing', 'Wise', 'All-seeing'],
    antonyms: ['Unknowing', 'Ignorant'],
    mnemonic: 'Omni (all) + Scient (science/knowing) -> Knowing all.',
  },

  // Idioms & Phrases
  {
    id: 'v-idm-1',
    word: 'At one’s wit’s end',
    meaning: 'Completely puzzled or perplexed; not knowing what to do next.',
    type: 'idiom',
    category: 'Mental State',
    example: 'Having tried every trouble-shooting technique, the engineer was at his wit’s end.',
    synonyms: ['Perplexed', 'Flummoxed', 'Baffled'],
    antonyms: ['Composed', 'Confident'],
  },
  {
    id: 'v-idm-2',
    word: 'Burn the midnight oil',
    meaning: 'To work or study late into the night.',
    type: 'idiom',
    category: 'Work & Diligence',
    example: 'Danish is burning the midnight oil every day to master SSC CGL Mathematics.',
    synonyms: ['Study tirelessly', 'Work late'],
    antonyms: ['Slack off', 'Idleness'],
  },
  {
    id: 'v-idm-3',
    word: 'A red-letter day',
    meaning: 'An auspicious, memorable, or extraordinarily important day.',
    type: 'idiom',
    category: 'Events & Milestones',
    example: 'The day she receives her appointment letter as Assistant Section Officer will be a red-letter day.',
    synonyms: ['Memorable day', 'Historic occasion'],
    antonyms: ['Insignificant day'],
  },
  {
    id: 'v-idm-4',
    word: 'Spill the beans',
    meaning: 'To disclose a secret prematurely or indiscreetly.',
    type: 'idiom',
    category: 'Communication',
    example: 'Do not tell him about the surprise celebration because he is known to spill the beans.',
    synonyms: ['Let the cat out of the bag', 'Divulge', 'Reveal'],
    antonyms: ['Keep secret', 'Conceal'],
  },

  // Synonyms & Antonyms
  {
    id: 'v-syn-1',
    word: 'Aberration',
    meaning: 'A departure from what is normal, usual, or expected, typically an unwelcome one.',
    type: 'synonym',
    category: 'Standard Deviations',
    example: 'The sudden dip in mock test score was merely a temporary aberration due to fatigue.',
    synonyms: ['Anomaly', 'Divergence', 'Deviation', 'Eccentricity'],
    antonyms: ['Normality', 'Conformity', 'Regularity'],
  },
  {
    id: 'v-syn-2',
    word: 'Cacophony',
    meaning: 'A harsh, discordant mixture of sounds.',
    type: 'synonym',
    category: 'Sounds & Sensory',
    example: 'The cacophony of blaring horns during rush hour made concentration impossible.',
    synonyms: ['Clamour', 'Dissonance', 'Din', 'Discord'],
    antonyms: ['Euphony', 'Harmony', 'Symphony'],
  },
  {
    id: 'v-ant-1',
    word: 'Taciturn',
    meaning: 'Reserved or uncommunicative in speech; saying little.',
    type: 'antonym',
    category: 'Speech & Communication',
    example: 'Unlike his boisterous and loquacious brother, the officer was remarkably taciturn.',
    synonyms: ['Reticent', 'Laconic', 'Reserved', 'Quiet'],
    antonyms: ['Loquacious', 'Garrulous', 'Voluble', 'Talkative'],
  },
  {
    id: 'v-ant-2',
    word: 'Mundane',
    meaning: 'Lacking interest or excitement; dull and ordinary.',
    type: 'antonym',
    category: 'Qualities & Existence',
    example: 'After a year of international travel, returning to mundane desk duties was challenging.',
    synonyms: ['Humdrum', 'Prosaic', 'Commonplace', 'Routine'],
    antonyms: ['Extraordinary', 'Exotic', 'Fascinating'],
  },

  // Commonly Confused Words
  {
    id: 'v-cfw-1',
    word: 'Compliment vs Complement',
    meaning: 'Compliment: expression of praise. Complement: something that completes or pairs perfectly.',
    type: 'confusing-word',
    category: 'Grammar Precision',
    example: 'The captain paid her a sincere compliment; the side-salad was an ideal complement to the dish.',
    synonyms: ['Praise vs Enhancement'],
    antonyms: [],
    mnemonic: 'Compl-I-ment has "I" (I like to receive praise). Compl-E-ment has "E" for Complete.',
  },
  {
    id: 'v-cfw-2',
    word: 'Emigrate vs Immigrate',
    meaning: 'Emigrate: to leave one’s own country (Exit). Immigrate: to come into a new country (In).',
    type: 'confusing-word',
    category: 'Grammar Precision',
    example: 'His grandfather emigrated from Poland in 1948 and immigrated to Canada.',
    synonyms: ['Exit vs Enter'],
    antonyms: [],
    mnemonic: 'E-migrate = Exit. I-mmigrate = In.',
  },

  // Spellings
  {
    id: 'v-spl-1',
    word: 'Accommodate',
    meaning: 'Provide lodging or sufficient space for; fit in with.',
    type: 'spelling',
    category: 'Spelling Traps',
    example: 'The new training centre can easily accommodate three hundred officers.',
    synonyms: [],
    antonyms: [],
    mnemonic: 'Contains double C and double M: a-CC-o-MM-odate (Two Cats and Two Mice).',
  },
  {
    id: 'v-spl-2',
    word: 'Millennium',
    meaning: 'A period of a thousand years.',
    type: 'spelling',
    category: 'Spelling Traps',
    example: 'The ancient ruins have withstood elements across a full millennium.',
    synonyms: [],
    antonyms: [],
    mnemonic: 'Contains double L and double N: mi-LL-e-NN-ium.',
  },
];
